/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_ACC_Streamer_h
#define AC_ACC_Streamer_h

#define AC_ACC_Variables \
private: \
  ClustersVector fClusters; \
  RawSideVector fRawSides; \
public: \
  ACC() \
    : fClusters() \
    , fRawSides() \
  { \
  }

#endif // AC_ACC_Streamer_h
