/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "ACC.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const ACC& object) {

  stream << object.fClusters;
  stream << object.fRawSides;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, ACC& object) {

  stream >> object.fClusters;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fRawSides;
  return stream;
}

}

}
