/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "ACCCluster.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const ACCCluster& object) {

  stream << object.fStatus;
  stream << object.fPhi;
  stream << object.fZ;
  stream << object.fTime;
  stream << object.fEnergy;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, ACCCluster& object) {

  stream >> object.fStatus;

  FloatArrayStream<4> subStream1(stream);
  object.fPhi = subStream1.read();
  object.fZ = subStream1.read();
  object.fTime = subStream1.read();
  object.fEnergy = subStream1.read();

  return stream;
}

}

}
