/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_ACCCluster_Streamer_h
#define AC_ACCCluster_Streamer_h

#define AC_ACCCluster_Variables \
private: \
  UInt_t fStatus; \
  Float_t fPhi; \
  Float_t fZ; \
  Float_t fTime; \
  Float_t fEnergy; \
public: \
  ACCCluster() \
    : fStatus(0) \
    , fPhi(0) \
    , fZ(0) \
    , fTime(0) \
    , fEnergy(0) \
  { \
  }

#endif // AC_ACCCluster_Streamer_h
