/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "ACCRawSide.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const ACCRawSide& object) {

  stream << object.fHWAddress;
  stream << object.fStatus;
  stream << object.fTemperature;
  stream << object.fADC;
  stream << object.fFTDCHits;
  stream << object.fTDCTimes;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, ACCRawSide& object) {


  UCharArrayStream<2> subStream1(stream);
  object.fHWAddress = subStream1.read();
  object.fStatus = subStream1.read();


  FloatArrayStream<2> subStream2(stream);
  object.fTemperature = subStream2.read();
  object.fADC = subStream2.read();

  stream >> object.fFTDCHits;
  stream >> object.fTDCTimes;
  return stream;
}

}

}
