/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "DAQ.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const DAQ& object) {

  stream << object.fL3Errors;
  stream << object.fJINJStatus;
  stream << object.fSlaveStatus;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, DAQ& object) {

  stream >> object.fL3Errors;
  stream >> object.fJINJStatus;
  stream >> object.fSlaveStatus;
  return stream;
}

}

}
