/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_DAQ_Streamer_h
#define AC_DAQ_Streamer_h

#define AC_DAQ_Variables \
private: \
  ULong64_t fL3Errors; \
  JINJStatusVector fJINJStatus; \
  SlaveStatusVector fSlaveStatus; \
public: \
  DAQ() \
    : fL3Errors(0) \
    , fJINJStatus() \
    , fSlaveStatus() \
  { \
  }

#endif // AC_DAQ_Streamer_h
