/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_ECAL_Streamer_h
#define AC_ECAL_Streamer_h

#define AC_ECAL_Variables \
private: \
  ShowersVector fShowers; \
public: \
  ECAL() \
    : fShowers() \
  { \
  }

#endif // AC_ECAL_Streamer_h
