/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_ECALShower_Streamer_h
#define AC_ECALShower_Streamer_h

#define AC_ECALShower_Variables \
private: \
  UInt_t fStatus; \
  UShort_t fNumberOfHits; \
  Float_t fDepositedEnergy; \
  Float_t fEnergyAt3CMRatio; \
  Float_t fReconstructedEnergy; \
  Float_t fReconstructedEnergyError; \
  Float_t fReconstructedEnergyElectron; \
  Float_t fReconstructedEnergyPhoton; \
  Float_t fReconstructedEnergyStandaloneEstimator; \
  Float_t fRelativeRearLeak; \
  Float_t fShowerMaximum; \
  Float_t fChiSquareProfile; \
  Float_t fTheta; \
  Float_t fPhi; \
  Float_t fX; \
  Float_t fY; \
  Float_t fZ; \
  Float_t fEntryX; \
  Float_t fEntryY; \
  Float_t fEntryZ; \
  Float_t fExitX; \
  Float_t fExitY; \
  Float_t fExitZ; \
  EstimatorsVector fEstimators; \
public: \
  ECALShower() \
    : fStatus(0) \
    , fNumberOfHits(0) \
    , fDepositedEnergy(0) \
    , fEnergyAt3CMRatio(0) \
    , fReconstructedEnergy(0) \
    , fReconstructedEnergyError(0) \
    , fReconstructedEnergyElectron(0) \
    , fReconstructedEnergyPhoton(0) \
    , fReconstructedEnergyStandaloneEstimator(0) \
    , fRelativeRearLeak(0) \
    , fShowerMaximum(0) \
    , fChiSquareProfile(0) \
    , fTheta(0) \
    , fPhi(0) \
    , fX(0) \
    , fY(0) \
    , fZ(0) \
    , fEntryX(0) \
    , fEntryY(0) \
    , fEntryZ(0) \
    , fExitX(0) \
    , fExitY(0) \
    , fExitZ(0) \
    , fEstimators() \
  { \
  }

#endif // AC_ECALShower_Streamer_h
