/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "ECALShower.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const ECALShower& object) {

  stream << object.fStatus;
  stream << object.fNumberOfHits;
  stream << object.fDepositedEnergy;
  stream << object.fEnergyAt3CMRatio;
  stream << object.fReconstructedEnergy;
  stream << object.fReconstructedEnergyError;
  stream << object.fReconstructedEnergyElectron;
  stream << object.fReconstructedEnergyPhoton;
  stream << object.fReconstructedEnergyStandaloneEstimator;
  stream << object.fRelativeRearLeak;
  stream << object.fShowerMaximum;
  stream << object.fChiSquareProfile;
  stream << object.fTheta;
  stream << object.fPhi;
  stream << object.fX;
  stream << object.fY;
  stream << object.fZ;
  stream << object.fEntryX;
  stream << object.fEntryY;
  stream << object.fEntryZ;
  stream << object.fExitX;
  stream << object.fExitY;
  stream << object.fExitZ;
  stream << object.fEstimators;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, ECALShower& object) {

  stream >> object.fStatus;
  stream >> object.fNumberOfHits;

  FloatArrayStream<4> subStream1(stream);
  object.fDepositedEnergy = subStream1.read();
  object.fEnergyAt3CMRatio = subStream1.read();
  object.fReconstructedEnergy = subStream1.read();
  object.fReconstructedEnergyError = subStream1.read();

  if (::AC::CurrentACQtVersion() >= 56)
    stream >> object.fReconstructedEnergyElectron;
  if (::AC::CurrentACQtVersion() >= 56)
    stream >> object.fReconstructedEnergyPhoton;
  if (::AC::CurrentACQtVersion() >= 58)
    stream >> object.fReconstructedEnergyStandaloneEstimator;

  FloatArrayStream<14> subStream2(stream);
  object.fRelativeRearLeak = subStream2.read();
  object.fShowerMaximum = subStream2.read();
  object.fChiSquareProfile = subStream2.read();
  object.fTheta = subStream2.read();
  object.fPhi = subStream2.read();
  object.fX = subStream2.read();
  object.fY = subStream2.read();
  object.fZ = subStream2.read();
  object.fEntryX = subStream2.read();
  object.fEntryY = subStream2.read();
  object.fEntryZ = subStream2.read();
  object.fExitX = subStream2.read();
  object.fExitY = subStream2.read();
  object.fExitZ = subStream2.read();

  stream >> object.fEstimators;
  return stream;
}

}

}
