/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_Event_Streamer_h
#define AC_Event_Streamer_h

#define AC_Event_Variables \
private: \
  AC::EventHeader fEventHeader; \
  ParticlesVector fParticles; \
  AC::Trigger fTrigger; \
  AC::DAQ fDAQ; \
  AC::TOF fTOF; \
  AC::ACC fACC; \
  AC::TRD fTRD; \
  AC::Tracker fTracker; \
  AC::RICH fRICH; \
  AC::ECAL fECAL; \
  AC::MC fMC; \
public: \
  Event() \
    : fEventHeader() \
    , fParticles() \
    , fTrigger() \
    , fDAQ() \
    , fTOF() \
    , fACC() \
    , fTRD() \
    , fTracker() \
    , fRICH() \
    , fECAL() \
    , fMC() \
  { \
  }

#endif // AC_Event_Streamer_h
