/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "Event.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const Event& object) {

  stream << object.fEventHeader;
  stream << object.fParticles;
  stream << object.fTrigger;
  stream << object.fDAQ;
  stream << object.fTOF;
  stream << object.fACC;
  stream << object.fTRD;
  stream << object.fTracker;
  stream << object.fRICH;
  stream << object.fECAL;
  stream << object.fMC;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, Event& object) {

  stream >> object.fEventHeader;
  stream >> object.fParticles;
  stream >> object.fTrigger;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fDAQ;
  stream >> object.fTOF;
  stream >> object.fACC;
  stream >> object.fTRD;
  stream >> object.fTracker;
  stream >> object.fRICH;
  stream >> object.fECAL;
  stream >> object.fMC;
  return stream;
}

}

}
