[Description]
Namespace = AC
Class = EventHeader
Members = \
  qint64 fAMSStatus                   \
  [57+UChar_t fFlags]                 \
  UChar_t fRandom                     \
  UChar_t fMCRandomSeed1              \
  UChar_t fMCRandomSeed2              \
  Int_t fEvent                        \
  TTimeStamp fTimeStamp               \
  [53_56Float_t fUTCTime]             \
  [57+TTimeStamp fUTCTimeStamp]       \
  [53-Float_t fGalacticLatitude]      \
  [53-Float_t fGalacticLongitude]     \
  Float_t fMagneticLatitude           \
  Float_t fMagneticLongitude          \
  Float_t fISSLatitude                \
  Float_t fISSLongitude               \
  Float_t fISSDistanceFromEarthCenter \
  Float_t fISSRoll                    \
  Float_t fISSPitch                   \
  Float_t fISSYaw                     \
  Float_t fISSVelocityLatitude        \
  Float_t fISSVelocityLongitude       \
  [54_55Float_t fMaxCutOffConeNegative] \
  [54_55Float_t fMaxCutOffConePositive]
