/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "EventHeader.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const EventHeader& object) {

  stream << object.fAMSStatus;
  stream << object.fFlags;
  stream << object.fRandom;
  stream << object.fMCRandomSeed1;
  stream << object.fMCRandomSeed2;
  stream << object.fEvent;
  stream << object.fTimeStamp;
  stream << object.fUTCTimeStamp;
  stream << object.fMagneticLatitude;
  stream << object.fMagneticLongitude;
  stream << object.fISSLatitude;
  stream << object.fISSLongitude;
  stream << object.fISSDistanceFromEarthCenter;
  stream << object.fISSRoll;
  stream << object.fISSPitch;
  stream << object.fISSYaw;
  stream << object.fISSVelocityLatitude;
  stream << object.fISSVelocityLongitude;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, EventHeader& object) {

  stream >> object.fAMSStatus;
  if (::AC::CurrentACQtVersion() >= 57)
    stream >> object.fFlags;

  UCharArrayStream<3> subStream1(stream);
  object.fRandom = subStream1.read();
  object.fMCRandomSeed1 = subStream1.read();
  object.fMCRandomSeed2 = subStream1.read();

  stream >> object.fEvent;
  stream >> object.fTimeStamp;
  if (::AC::CurrentACQtVersion() >= 53 && ::AC::CurrentACQtVersion() <= 56)
    stream >> object.fUTCTime;
  if (::AC::CurrentACQtVersion() >= 57)
    stream >> object.fUTCTimeStamp;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fGalacticLatitude;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fGalacticLongitude;

  FloatArrayStream<10> subStream2(stream);
  object.fMagneticLatitude = subStream2.read();
  object.fMagneticLongitude = subStream2.read();
  object.fISSLatitude = subStream2.read();
  object.fISSLongitude = subStream2.read();
  object.fISSDistanceFromEarthCenter = subStream2.read();
  object.fISSRoll = subStream2.read();
  object.fISSPitch = subStream2.read();
  object.fISSYaw = subStream2.read();
  object.fISSVelocityLatitude = subStream2.read();
  object.fISSVelocityLongitude = subStream2.read();

  if (::AC::CurrentACQtVersion() >= 54 && ::AC::CurrentACQtVersion() <= 55)
    stream >> object.fMaxCutOffConeNegative;
  if (::AC::CurrentACQtVersion() >= 54 && ::AC::CurrentACQtVersion() <= 55)
    stream >> object.fMaxCutOffConePositive;
  return stream;
}

}

}
