/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_EventHeader_Streamer_h
#define AC_EventHeader_Streamer_h

#define AC_EventHeader_Variables \
private: \
  qint64 fStatus; \
  UChar_t fRandom; \
  UChar_t fMCRandomSeed1; \
  UChar_t fMCRandomSeed2; \
  Int_t fEvent; \
  TTimeStamp fTimeStamp; \
  Double_t fUTCTime; \
  Float_t fGalacticLatitude; \
  Float_t fGalacticLongitude; \
  Float_t fMagneticLatitude; \
  Float_t fMagneticLongitude; \
  Float_t fISSLatitude; \
  Float_t fISSLongitude; \
  Float_t fISSDistanceFromEarthCenter; \
  Float_t fISSRoll; \
  Float_t fISSPitch; \
  Float_t fISSYaw; \
  Float_t fISSVelocityLatitude; \
  Float_t fISSVelocityLongitude; \
  Float_t fMaxCutOffConeNegative; \
  Float_t fMaxCutOffConePositive; \
public: \
  EventHeader() \
    : fStatus(0) \
    , fRandom(0) \
    , fMCRandomSeed1(0) \
    , fMCRandomSeed2(0) \
    , fEvent(0) \
    , fTimeStamp(0) \
    , fUTCTime(0) \
    , fGalacticLatitude(0) \
    , fGalacticLongitude(0) \
    , fMagneticLatitude(0) \
    , fMagneticLongitude(0) \
    , fISSLatitude(0) \
    , fISSLongitude(0) \
    , fISSDistanceFromEarthCenter(0) \
    , fISSRoll(0) \
    , fISSPitch(0) \
    , fISSYaw(0) \
    , fISSVelocityLatitude(0) \
    , fISSVelocityLongitude(0) \
    , fMaxCutOffConeNegative(0) \
    , fMaxCutOffConePositive(0) \
  { \
  }

#endif // AC_EventHeader_Streamer_h
