/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "MC.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const MC& object) {

  stream << object.fEventGenerators;
  stream << object.fTracks;
  stream << object.fTRDHits;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, MC& object) {

  stream >> object.fEventGenerators;
  stream >> object.fTracks;
  stream >> object.fTRDHits;
  return stream;
}

}

}
