/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_MC_Streamer_h
#define AC_MC_Streamer_h

#define AC_MC_Variables \
private: \
  EventGeneratorsVector fEventGenerators; \
  TracksVector fTracks; \
  TrackerClustersVector fTrackerClusters; \
  TRDClustersVector fTRDClusters; \
  Int_t fNumberOfEventGenerators; \
  Int_t fNumberOfTrackerCluster; \
  Int_t fNumberOfTRDCluster; \
  Int_t fNumberOfTOFCluster; \
  Int_t fNumberOfACCCluster; \
  Int_t fNumberOfRICHCluster; \
  Int_t fNumberOfECALHits; \
  Float_t fUpperTOFEnergyDeposition; \
  Float_t fLowerTOFEnergyDeposition; \
  Float_t fTrackerEnergyDeposition; \
  Float_t fTRDEnergyDeposition; \
  Float_t fACCEnergyDeposition; \
  Float_t fECALEnergyDeposition; \
public: \
  MC() \
    : fEventGenerators() \
    , fTracks() \
    , fTrackerClusters() \
    , fTRDClusters() \
    , fNumberOfEventGenerators(0) \
    , fNumberOfTrackerCluster(0) \
    , fNumberOfTRDCluster(0) \
    , fNumberOfTOFCluster(0) \
    , fNumberOfACCCluster(0) \
    , fNumberOfRICHCluster(0) \
    , fNumberOfECALHits(0) \
    , fUpperTOFEnergyDeposition(0) \
    , fLowerTOFEnergyDeposition(0) \
    , fTrackerEnergyDeposition(0) \
    , fTRDEnergyDeposition(0) \
    , fACCEnergyDeposition(0) \
    , fECALEnergyDeposition(0) \
  { \
  }

#endif // AC_MC_Streamer_h
