/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_MC_Streamer_h
#define AC_MC_Streamer_h

#define AC_MC_Variables \
private: \
  EventGeneratorsVector fEventGenerators; \
  TracksVector fTracks; \
  TRDHitsVector fTRDHits; \
public: \
  MC() \
    : fEventGenerators() \
    , fTracks() \
    , fTRDHits() \
  { \
  }

#endif // AC_MC_Streamer_h
