/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "MCEventGenerator.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const MCEventGenerator& object) {

  stream << object.fParticleID;
  stream << object.fTrackID;
  stream << object.fMotherParticle;
  stream << object.fProcess;
  stream << object.fMomentum;
  stream << object.fMass;
  stream << object.fCharge;
  stream << object.fX0;
  stream << object.fY0;
  stream << object.fZ0;
  stream << object.fTheta;
  stream << object.fPhi;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, MCEventGenerator& object) {

  if (::AC::CurrentACQtVersion() < 55)
    stream >> object.fID;
  if (::AC::CurrentACQtVersion() >= 55)
    stream >> object.fParticleID;
  if (::AC::CurrentACQtVersion() >= 55)
    stream >> object.fTrackID;
  stream >> object.fMotherParticle;
  stream >> object.fProcess;

  FloatArrayStream<8> subStream1(stream);
  object.fMomentum = subStream1.read();
  object.fMass = subStream1.read();
  object.fCharge = subStream1.read();
  object.fX0 = subStream1.read();
  object.fY0 = subStream1.read();
  object.fZ0 = subStream1.read();
  object.fTheta = subStream1.read();
  object.fPhi = subStream1.read();

  return stream;
}

}

}
