/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "MCEventGenerator.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const MCEventGenerator& object) {

  stream << object.fID;
  stream << object.fMotherParticle;
  stream << object.fProcess;
  stream << object.fMomentum;
  stream << object.fMass;
  stream << object.fCharge;
  stream << object.fX0;
  stream << object.fY0;
  stream << object.fZ0;
  stream << object.fTheta;
  stream << object.fPhi;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, MCEventGenerator& object) {


  UShortArrayStream<2> subStream1(stream);
  object.fID = subStream1.read();
  object.fMotherParticle = subStream1.read();

  stream >> object.fProcess;

  FloatArrayStream<8> subStream2(stream);
  object.fMomentum = subStream2.read();
  object.fMass = subStream2.read();
  object.fCharge = subStream2.read();
  object.fX0 = subStream2.read();
  object.fY0 = subStream2.read();
  object.fZ0 = subStream2.read();
  object.fTheta = subStream2.read();
  object.fPhi = subStream2.read();

  return stream;
}

}

}
