/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_MCEventGenerator_Streamer_h
#define AC_MCEventGenerator_Streamer_h

#define AC_MCEventGenerator_Variables \
private: \
  UShort_t fID; \
  UShort_t fMotherParticle; \
  UChar_t fProcess; \
  Float_t fMomentum; \
  Float_t fMass; \
  Float_t fCharge; \
  Float_t fX0; \
  Float_t fY0; \
  Float_t fZ0; \
  Float_t fTheta; \
  Float_t fPhi; \
public: \
  MCEventGenerator() \
    : fID(0) \
    , fMotherParticle(0) \
    , fProcess(0) \
    , fMomentum(0) \
    , fMass(0) \
    , fCharge(0) \
    , fX0(0) \
    , fY0(0) \
    , fZ0(0) \
    , fTheta(0) \
    , fPhi(0) \
  { \
  }

#endif // AC_MCEventGenerator_Streamer_h
