[Description]
Namespace = AC
Class = MCEventGenerator
Members = \
  [55-UShort_t fID]        \
  [55+Short_t fParticleID] \
  [55+UShort_t fTrackID]   \
  UShort_t fMotherParticle \
  UChar_t fProcess         \
  Float_t fMomentum        \
  Float_t fMass            \
  Float_t fCharge          \
  Float_t fX0              \
  Float_t fY0              \
  Float_t fZ0              \
  Float_t fTheta           \
  Float_t fPhi
