/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_MCTrackerCluster_Streamer_h
#define AC_MCTrackerCluster_Streamer_h

#define AC_MCTrackerCluster_Variables \
private: \
  Short_t fID; \
  Float_t fDepositedEnergy; \
  Float_t fMCParticleMomentum; \
  Float_t fX; \
  Float_t fY; \
  Float_t fZ; \
public: \
  MCTrackerCluster() \
    : fID(0) \
    , fDepositedEnergy(0) \
    , fMCParticleMomentum(0) \
    , fX(0) \
    , fY(0) \
    , fZ(0) \
  { \
  }

#endif // AC_MCTrackerCluster_Streamer_h
