/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "MCTrackerCluster.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const MCTrackerCluster& object) {

  stream << object.fID;
  stream << object.fDepositedEnergy;
  stream << object.fMCParticleMomentum;
  stream << object.fX;
  stream << object.fY;
  stream << object.fZ;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, MCTrackerCluster& object) {

  stream >> object.fID;

  FloatArrayStream<5> subStream1(stream);
  object.fDepositedEnergy = subStream1.read();
  object.fMCParticleMomentum = subStream1.read();
  object.fX = subStream1.read();
  object.fY = subStream1.read();
  object.fZ = subStream1.read();

  return stream;
}

}

}
