/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_MCTrack_Streamer_h
#define AC_MCTrack_Streamer_h

#define AC_MCTrack_Variables \
private: \
  Char_t fVolumeName[5]; \
  Float_t fX0; \
  Float_t fY0; \
  Float_t fZ0; \
public: \
  MCTrack() \
    : fX0(0) \
    , fY0(0) \
    , fZ0(0) \
  { \
    for (unsigned int i = 0; i < 5; ++i) \
      fVolumeName[i] = 0; \
  }

#endif // AC_MCTrack_Streamer_h
