[Description]
Namespace = AC
Class = MCTRDHit
Members = \
  Short_t fID                  \
  UShort_t fLLT                \
  EnergyLossVector fEnergyLoss \
  Float_t fKineticEnergy       \
  Float_t fDepositedEnergy     \
  Float_t fStep
