/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "MCTRDCluster.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const MCTRDCluster& object) {

  stream << object.fID;
  stream << object.fLLT;
  stream << object.fEnergyLoss;
  stream << object.fKineticEnergy;
  stream << object.fDepositedEnergy;
  stream << object.fStep;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, MCTRDCluster& object) {

  stream >> object.fID;
  stream >> object.fLLT;
  stream >> object.fEnergyLoss;

  FloatArrayStream<3> subStream1(stream);
  object.fKineticEnergy = subStream1.read();
  object.fDepositedEnergy = subStream1.read();
  object.fStep = subStream1.read();

  return stream;
}

}

}
