/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "MCTrack.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const MCTrack& object) {

  stream.writeRawData(object.fVolumeName, 5);
  stream << object.fX0;
  stream << object.fY0;
  stream << object.fZ0;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, MCTrack& object) {

  stream.readRawData(object.fVolumeName, 5);

  FloatArrayStream<3> subStream1(stream);
  object.fX0 = subStream1.read();
  object.fY0 = subStream1.read();
  object.fZ0 = subStream1.read();

  return stream;
}

}

}
