/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_Particle_Streamer_h
#define AC_Particle_Streamer_h

#define AC_Particle_Variables \
private: \
  UShort_t fStatus; \
  Float_t fStoermerCutoffNegative; \
  Float_t fStoermerCutoffPositive; \
  Float_t fGalacticLongitudeFromBacktracing; \
  Float_t fGalacticLatitudeFromBacktracing; \
  Float_t fGalacticLongitudeFromOrbit; \
  Float_t fGalacticLatitudeFromOrbit; \
  Int_t fID; \
  Float_t fIDProbability; \
  Float_t fMomentum; \
  Float_t fMomentumError; \
  Float_t fMass; \
  Float_t fMassError; \
  Float_t fBeta; \
  Float_t fBetaError; \
  ChargesVector fCharges; \
  ChargesProbabilityVector fChargesProbability; \
  Short_t fTOFBetaIndex; \
  Short_t fTRDVTrackIndex; \
  Short_t fTRDHTrackIndex; \
  Short_t fTrackerTrackIndex; \
  Short_t fRICHRingIndex; \
  Short_t fECALShowerIndex; \
public: \
  Particle() \
    : fStatus(0) \
    , fStoermerCutoffNegative(0) \
    , fStoermerCutoffPositive(0) \
    , fGalacticLongitudeFromBacktracing(0) \
    , fGalacticLatitudeFromBacktracing(0) \
    , fGalacticLongitudeFromOrbit(0) \
    , fGalacticLatitudeFromOrbit(0) \
    , fID(0) \
    , fIDProbability(0) \
    , fMomentum(0) \
    , fMomentumError(0) \
    , fMass(0) \
    , fMassError(0) \
    , fBeta(0) \
    , fBetaError(0) \
    , fCharges() \
    , fChargesProbability() \
    , fTOFBetaIndex(0) \
    , fTRDVTrackIndex(0) \
    , fTRDHTrackIndex(0) \
    , fTrackerTrackIndex(0) \
    , fRICHRingIndex(0) \
    , fECALShowerIndex(0) \
  { \
  }

#endif // AC_Particle_Streamer_h
