/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "Particle.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const Particle& object) {

  stream << object.fStatus;
  stream << object.fStoermerCutoffNegative;
  stream << object.fStoermerCutoffPositive;
  stream << object.fGalacticLongitudeFromBacktracing;
  stream << object.fGalacticLatitudeFromBacktracing;
  stream << object.fGalacticLongitudeFromOrbit;
  stream << object.fGalacticLatitudeFromOrbit;
  stream << object.fTOFBetaIndex;
  stream << object.fTRDVTrackIndex;
  stream << object.fTRDHTrackIndex;
  stream << object.fTrackerTrackIndex;
  stream << object.fRICHRingIndex;
  stream << object.fECALShowerIndex;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, Particle& object) {

  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fStatus;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fStoermerCutoffNegative;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fStoermerCutoffPositive;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fGalacticLongitudeFromBacktracing;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fGalacticLatitudeFromBacktracing;
  if (::AC::CurrentACQtVersion() >= 54)
    stream >> object.fGalacticLongitudeFromOrbit;
  if (::AC::CurrentACQtVersion() >= 54)
    stream >> object.fGalacticLatitudeFromOrbit;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fID;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fIDProbability;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fMomentum;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fMomentumError;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fMass;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fMassError;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fBeta;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fBetaError;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fCharges;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fChargesProbability;

  ShortArrayStream<6> subStream1(stream);
  object.fTOFBetaIndex = subStream1.read();
  object.fTRDVTrackIndex = subStream1.read();
  object.fTRDHTrackIndex = subStream1.read();
  object.fTrackerTrackIndex = subStream1.read();
  object.fRICHRingIndex = subStream1.read();
  object.fECALShowerIndex = subStream1.read();

  return stream;
}

}

}
