[Description]
Namespace = AC
Class = Particle
Members = \
  [53+UShort_t fStatus]                             \
  [53+Float_t fStoermerCutoffNegative]              \
  [53+Float_t fStoermerCutoffPositive]              \
  [53+Float_t fGalacticLongitudeFromBacktracing]    \
  [53+Float_t fGalacticLatitudeFromBacktracing]     \
  [54+Float_t fGalacticLongitudeFromOrbit]          \
  [54+Float_t fGalacticLatitudeFromOrbit]           \
  [53-Int_t fID]                                    \
  [53-Float_t fIDProbability]                       \
  [53-Float_t fMomentum]                            \
  [53-Float_t fMomentumError]                       \
  [53-Float_t fMass]                                \
  [53-Float_t fMassError]                           \
  [53-Float_t fBeta]                                \
  [53-Float_t fBetaError]                           \
  [53-ChargesVector fCharges]                       \
  [53-ChargesProbabilityVector fChargesProbability] \
  Short_t fTOFBetaIndex                             \
  Short_t fTRDVTrackIndex                           \
  Short_t fTRDHTrackIndex                           \
  Short_t fTrackerTrackIndex                        \
  Short_t fRICHRingIndex                            \
  Short_t fECALShowerIndex
