/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_RICH_Streamer_h
#define AC_RICH_Streamer_h

#define AC_RICH_Variables \
private: \
  RingsVector fRings; \
public: \
  RICH() \
    : fRings() \
  { \
  }

#endif // AC_RICH_Streamer_h
