/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "RICHRing.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const RICHRing& object) {

  stream << object.fStatus;
  stream << object.fNumberOfHits;
  stream << object.fBeta;
  stream << object.fBetaError;
  stream << object.fX;
  stream << object.fY;
  stream << object.fZ;
  stream << object.fTheta;
  stream << object.fPhi;
  stream << object.fProbability;
  stream << object.fChargeEstimate;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, RICHRing& object) {

  stream >> object.fStatus;
  stream >> object.fNumberOfHits;

  FloatArrayStream<9> subStream1(stream);
  object.fBeta = subStream1.read();
  object.fBetaError = subStream1.read();
  object.fX = subStream1.read();
  object.fY = subStream1.read();
  object.fZ = subStream1.read();
  object.fTheta = subStream1.read();
  object.fPhi = subStream1.read();
  object.fProbability = subStream1.read();
  object.fChargeEstimate = subStream1.read();

  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fCharges;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fChargesProbability;
  return stream;
}

}

}
