/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_RunHeader_Streamer_h
#define AC_RunHeader_Streamer_h

#define AC_RunHeader_Variables \
private: \
  UShort_t fRunTag; \
  UShort_t fRunType; \
  Int_t fRun; \
  Int_t fTotalAMSEvents; \
  TTimeStamp fFirstEventTimeStamp; \
  TTimeStamp fLastEventTimeStamp; \
  UShort_t fTRDHighVoltage; \
  UShort_t fAMSPatchVersion; \
  Char_t fAMSPassNumber; \
  UChar_t fACRootVersion; \
  TTimeStamp fProducerJobTimeStamp; \
  std::string fAMSRootFileName; \
  std::string fGitSHA; \
  StreamsVector fSelectedStreams; \
  ULong64_t fMCNumberOfTriggeredEvents; \
  Float_t fMCMinimumMomentum; \
  Float_t fMCMaximumMomentum; \
public: \
  RunHeader() \
    : fRunTag(0) \
    , fRunType(0) \
    , fRun(0) \
    , fTotalAMSEvents(0) \
    , fFirstEventTimeStamp(0) \
    , fLastEventTimeStamp(0) \
    , fTRDHighVoltage(0) \
    , fAMSPatchVersion(0) \
    , fAMSPassNumber(0) \
    , fACRootVersion(0) \
    , fProducerJobTimeStamp(0) \
    , fAMSRootFileName() \
    , fGitSHA() \
    , fSelectedStreams() \
    , fMCNumberOfTriggeredEvents(0) \
    , fMCMinimumMomentum(0) \
    , fMCMaximumMomentum(0) \
  { \
  }

#endif // AC_RunHeader_Streamer_h
