/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_RunHeader_Streamer_h
#define AC_RunHeader_Streamer_h

#define AC_RunHeader_Variables \
private: \
  UShort_t fRunTag; \
  Int_t fRun; \
  Int_t fTotalAMSEvents; \
  TTimeStamp fFirstEventTimeStamp; \
  TTimeStamp fLastEventTimeStamp; \
  UShort_t fTRDHighVoltage; \
  UShort_t fAMSPatchVersion; \
  Char_t fAMSPassNumber; \
  UChar_t fACRootVersion; \
  TTimeStamp fProducerJobTimeStamp; \
  std::string fAMSRootFileName; \
  std::string fGitSHA; \
  StreamsVector fSelectedStreams; \
public: \
  RunHeader() \
    : fRunTag(0) \
    , fRun(0) \
    , fTotalAMSEvents(0) \
    , fFirstEventTimeStamp(0) \
    , fLastEventTimeStamp(0) \
    , fTRDHighVoltage(0) \
    , fAMSPatchVersion(0) \
    , fAMSPassNumber(0) \
    , fACRootVersion(0) \
    , fProducerJobTimeStamp(0) \
    , fAMSRootFileName() \
    , fGitSHA() \
    , fSelectedStreams() \
  { \
  }

#endif // AC_RunHeader_Streamer_h
