[Description]
Namespace = AC
Class = RunHeader
Members = \
  UShort_t fRunTag                 \
  [56+UShort_t fRunType]           \
  Int_t fRun                       \
  Int_t fTotalAMSEvents            \
  TTimeStamp fFirstEventTimeStamp  \
  TTimeStamp fLastEventTimeStamp   \
  UShort_t fTRDHighVoltage         \
  UShort_t fAMSPatchVersion        \
  Char_t fAMSPassNumber            \
  UChar_t fACRootVersion           \
  TTimeStamp fProducerJobTimeStamp \
  std::string fAMSRootFileName     \
  std::string fGitSHA              \
  StreamsVector fSelectedStreams   \
  [56+ULong64_t fMCNumberOfTriggeredEvents] \
  [57+Float_t fMCMinimumMomentum] \
  [57+Float_t fMCMaximumMomentum]
