/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "RunHeader.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const RunHeader& object) {

  stream << object.fRunTag;
  stream << object.fRun;
  stream << object.fTotalAMSEvents;
  stream << object.fFirstEventTimeStamp;
  stream << object.fLastEventTimeStamp;
  stream << object.fTRDHighVoltage;
  stream << object.fAMSPatchVersion;
  stream.writeRawData(&object.fAMSPassNumber, 1);
  stream << object.fACRootVersion;
  stream << object.fProducerJobTimeStamp;
  stream << object.fAMSRootFileName;
  stream << object.fGitSHA;
  stream << object.fSelectedStreams;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, RunHeader& object) {

  stream >> object.fRunTag;

  stream >> object.fRun
         >> object.fTotalAMSEvents;


  stream >> object.fFirstEventTimeStamp
         >> object.fLastEventTimeStamp;


  UShortArrayStream<2> subStream1(stream);
  object.fTRDHighVoltage = subStream1.read();
  object.fAMSPatchVersion = subStream1.read();

  stream.readRawData(&object.fAMSPassNumber, 1);
  stream >> object.fACRootVersion;
  stream >> object.fProducerJobTimeStamp;

  stream >> object.fAMSRootFileName
         >> object.fGitSHA;

  stream >> object.fSelectedStreams;
  return stream;
}

}

}
