/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TOF_Streamer_h
#define AC_TOF_Streamer_h

#define AC_TOF_Variables \
private: \
  BetasVector fBetas; \
  ClustersVector fClusters; \
public: \
  TOF() \
    : fBetas() \
    , fClusters() \
  { \
  }

#endif // AC_TOF_Streamer_h
