/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TOFBeta.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TOFBeta& object) {

  stream << object.fBeta;
  stream << object.fBetaError;
  stream.writeRawData(&object.fTrackerTrackIndex, 1);
  stream << object.fChargesNew;
  stream << object.fTOFClusterIndex;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TOFBeta& object) {


  FloatArrayStream<2> subStream1(stream);
  object.fBeta = subStream1.read();
  object.fBetaError = subStream1.read();

  if (::AC::CurrentACQtVersion() >= 57)
    stream.readRawData(&object.fTrackerTrackIndex, 1);
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fCharges;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fChargesProbability;
  stream >> object.fChargesNew;
  stream >> object.fTOFClusterIndex;
  return stream;
}

}

}
