[Description]
Namespace = AC
Class = TOFCluster
Members = \
  UInt_t fStatus       \
  UChar_t fLayerBar    \
  Float_t fX           \
  Float_t fY           \
  Float_t fZ           \
  Float_t fTime        \
  Float_t fTimeError   \
  Float_t fEnergy      \
  [57+Float_t fCharge]
