/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TOFCluster.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TOFCluster& object) {

  stream << object.fStatus;
  stream << object.fLayerBar;
  stream << object.fX;
  stream << object.fY;
  stream << object.fZ;
  stream << object.fTime;
  stream << object.fTimeError;
  stream << object.fEnergy;
  stream << object.fCharge;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TOFCluster& object) {

  stream >> object.fStatus;
  stream >> object.fLayerBar;

  FloatArrayStream<6> subStream1(stream);
  object.fX = subStream1.read();
  object.fY = subStream1.read();
  object.fZ = subStream1.read();
  object.fTime = subStream1.read();
  object.fTimeError = subStream1.read();
  object.fEnergy = subStream1.read();

  if (::AC::CurrentACQtVersion() >= 57)
    stream >> object.fCharge;
  return stream;
}

}

}
