/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TOFCluster_Streamer_h
#define AC_TOFCluster_Streamer_h

#define AC_TOFCluster_Variables \
private: \
  UInt_t fStatus; \
  UChar_t fLayerBar; \
  Float_t fX; \
  Float_t fY; \
  Float_t fZ; \
  Float_t fTime; \
  Float_t fTimeError; \
  Float_t fEnergy; \
  Float_t fCharge; \
public: \
  TOFCluster() \
    : fStatus(0) \
    , fLayerBar(0) \
    , fX(0) \
    , fY(0) \
    , fZ(0) \
    , fTime(0) \
    , fTimeError(0) \
    , fEnergy(0) \
    , fCharge(0) \
  { \
  }

#endif // AC_TOFCluster_Streamer_h
