/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TrackerTrack_Streamer_h
#define AC_TrackerTrack_Streamer_h

#define AC_TrackerTrack_Variables \
private: \
  UInt_t fStatus; \
  Int_t fNumberOfHitsX; \
  Int_t fNumberOfHitsY; \
  ChargesVector fCharges; \
  ChargesProbabilityVector fChargesProbability; \
  SCalibProbabilityVector fSCalibProbability; \
  Float_t fTrdKCharge; \
  Float_t fTrdKChargeError; \
  UChar_t fTrdKChargeNumberOfHitsForCharge; \
  UChar_t fTrdKChargeNumberOfHitsForNucleiPDF; \
  UChar_t fTrdKChargeNumberOfHitsForDeltaRayPDF; \
  TrdKChargeLikelihoodVector fTrdKChargeLikelihood; \
  UChar_t fTrdKChargeNumberOfHitsForLikelihoods; \
  UChar_t fTrdKChargeNumberOfOffTrackHitsForLikelihoods; \
  Float_t fCCLikelihood; \
  ChargesNewVector fChargesNew; \
  FitsVector fTrackFits; \
  ReconstructedHitsVector fReconstructedHits; \
  ClusterDistancesVector fClusterDistances; \
public: \
  TrackerTrack() \
    : fStatus(0) \
    , fNumberOfHitsX(0) \
    , fNumberOfHitsY(0) \
    , fCharges() \
    , fChargesProbability() \
    , fSCalibProbability() \
    , fTrdKCharge(0) \
    , fTrdKChargeError(0) \
    , fTrdKChargeNumberOfHitsForCharge(0) \
    , fTrdKChargeNumberOfHitsForNucleiPDF(0) \
    , fTrdKChargeNumberOfHitsForDeltaRayPDF(0) \
    , fTrdKChargeLikelihood() \
    , fTrdKChargeNumberOfHitsForLikelihoods(0) \
    , fTrdKChargeNumberOfOffTrackHitsForLikelihoods(0) \
    , fCCLikelihood(0) \
    , fChargesNew() \
    , fTrackFits() \
    , fReconstructedHits() \
    , fClusterDistances() \
  { \
  }

#endif // AC_TrackerTrack_Streamer_h
