[Description]
Namespace = AC
Class = TrackerTrack
Members = \
  UInt_t fStatus                                             \
  Int_t fNumberOfHitsX                                       \
  Int_t fNumberOfHitsY                                       \
  [53-ChargesVector fCharges]                                \
  [53-ChargesProbabilityVector fChargesProbability]          \
  [53-SCalibProbabilityVector fSCalibProbability]            \
  [53+Float_t fTrdKCharge]                                   \
  [53+Float_t fTrdKChargeError]                              \
  [53+UChar_t fTrdKChargeNumberOfHitsForCharge]              \
  [53+UChar_t fTrdKChargeNumberOfHitsForNucleiPDF]           \
  [53+UChar_t fTrdKChargeNumberOfHitsForDeltaRayPDF]         \
  [53+TrdKChargeLikelihoodVector fTrdKChargeLikelihood]      \
  [53+UChar_t fTrdKChargeNumberOfHitsForLikelihoods]         \
  [53+UChar_t fTrdKChargeNumberOfOffTrackHitsForLikelihoods] \
  ChargesNewVector fChargesNew                               \
  FitsVector fTrackFits                                      \
  ReconstructedHitsVector fReconstructedHits                 \
  ClusterDistancesVector fClusterDistances
