/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TrackerTrackFit.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TrackerTrackFit& object) {

  stream << object.fParameters;
  stream << object.fRigidity;
  stream << object.fInverseRigidityError;
  stream << object.fChiSquareNormalizedX;
  stream << object.fChiSquareNormalizedY;
  stream << object.fThetaLayer1;
  stream << object.fPhiLayer1;
  stream << object.fXLayer1;
  stream << object.fYLayer1;
  stream << object.fXLayer1Plus1cm;
  stream << object.fYLayer1Plus1cm;
  stream << object.fXTRDUpper;
  stream << object.fYTRDUpper;
  stream << object.fXTRDCenter;
  stream << object.fYTRDCenter;
  stream << object.fXTRDLower;
  stream << object.fYTRDLower;
  stream << object.fThetaTOFUpper;
  stream << object.fPhiTOFUpper;
  stream << object.fXTOFUpper;
  stream << object.fYTOFUpper;
  stream << object.fXTOFUpperMinus1cm;
  stream << object.fYTOFUpperMinus1cm;
  stream << object.fXLayer56;
  stream << object.fYLayer56;
  stream << object.fThetaRICH;
  stream << object.fPhiRICH;
  stream << object.fXRICH;
  stream << object.fYRICH;
  stream << object.fThetaLayer9;
  stream << object.fPhiLayer9;
  stream << object.fXLayer9;
  stream << object.fYLayer9;
  stream << object.fXLayer9Minus1cm;
  stream << object.fYLayer9Minus1cm;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TrackerTrackFit& object) {

  if (::AC::CurrentACQtVersion() < 55)
    stream >> object.fParametersOld;
  if (::AC::CurrentACQtVersion() >= 55)
    stream >> object.fParameters;

  FloatArrayStream<8> subStream1(stream);
  object.fRigidity = subStream1.read();
  object.fInverseRigidityError = subStream1.read();
  object.fChiSquareNormalizedX = subStream1.read();
  object.fChiSquareNormalizedY = subStream1.read();
  object.fThetaLayer1 = subStream1.read();
  object.fPhiLayer1 = subStream1.read();
  object.fXLayer1 = subStream1.read();
  object.fYLayer1 = subStream1.read();

  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fXLayer1Plus1cm;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fYLayer1Plus1cm;

  FloatArrayStream<10> subStream2(stream);
  object.fXTRDUpper = subStream2.read();
  object.fYTRDUpper = subStream2.read();
  object.fXTRDCenter = subStream2.read();
  object.fYTRDCenter = subStream2.read();
  object.fXTRDLower = subStream2.read();
  object.fYTRDLower = subStream2.read();
  object.fThetaTOFUpper = subStream2.read();
  object.fPhiTOFUpper = subStream2.read();
  object.fXTOFUpper = subStream2.read();
  object.fYTOFUpper = subStream2.read();

  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fXTOFUpperMinus1cm;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fYTOFUpperMinus1cm;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fXLayer56;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fYLayer56;

  FloatArrayStream<8> subStream3(stream);
  object.fThetaRICH = subStream3.read();
  object.fPhiRICH = subStream3.read();
  object.fXRICH = subStream3.read();
  object.fYRICH = subStream3.read();
  object.fThetaLayer9 = subStream3.read();
  object.fPhiLayer9 = subStream3.read();
  object.fXLayer9 = subStream3.read();
  object.fYLayer9 = subStream3.read();

  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fXLayer9Minus1cm;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fYLayer9Minus1cm;
  return stream;
}

}

}
