[Description]
Namespace = AC
Class = TrackerReconstructedHit
Members = \
  Char_t fLayer    \
  Float_t fX       \
  Float_t fY       \
  [55-Float_t fSignalX] \
  [55-Float_t fSignalY \
  [54+Short_t fResidualY] \
  [55+Float_t fQLayerJ]
