/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TrackerReconstructedHit.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TrackerReconstructedHit& object) {

  stream.writeRawData(&object.fLayer, 1);
  stream << object.fX;
  stream << object.fY;
  stream << object.fSignalX;
  stream << object.fSignalY;
  stream << object.fResidualY;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TrackerReconstructedHit& object) {

  stream.readRawData(&object.fLayer, 1);

  FloatArrayStream<4> subStream1(stream);
  object.fX = subStream1.read();
  object.fY = subStream1.read();
  object.fSignalX = subStream1.read();
  object.fSignalY = subStream1.read();

  if (::AC::CurrentACQtVersion() >= 54)
    stream >> object.fResidualY;
  return stream;
}

}

}
