/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TrackerTrack.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TrackerTrack& object) {

  stream << object.fStatus;
  stream << object.fNumberOfHitsX;
  stream << object.fNumberOfHitsY;
  stream << object.fTrdKCharge;
  stream << object.fTrdKChargeError;
  stream << object.fTrdKChargeNumberOfHitsForCharge;
  stream << object.fTrdKChargeNumberOfHitsForNucleiPDF;
  stream << object.fTrdKChargeNumberOfHitsForDeltaRayPDF;
  stream << object.fTrdKChargeLikelihood;
  stream << object.fTrdKChargeNumberOfHitsForLikelihoods;
  stream << object.fTrdKChargeNumberOfOffTrackHitsForLikelihoods;
  stream << object.fChargesNew;
  stream << object.fTrackFits;
  stream << object.fReconstructedHits;
  stream << object.fClusterDistances;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TrackerTrack& object) {

  stream >> object.fStatus;

  stream >> object.fNumberOfHitsX
         >> object.fNumberOfHitsY;

  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fCharges;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fChargesProbability;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fSCalibProbability;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fTrdKCharge;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fTrdKChargeError;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fTrdKChargeNumberOfHitsForCharge;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fTrdKChargeNumberOfHitsForNucleiPDF;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fTrdKChargeNumberOfHitsForDeltaRayPDF;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fTrdKChargeLikelihood;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fTrdKChargeNumberOfHitsForLikelihoods;
  if (::AC::CurrentACQtVersion() >= 53)
    stream >> object.fTrdKChargeNumberOfOffTrackHitsForLikelihoods;
  stream >> object.fChargesNew;
  stream >> object.fTrackFits;
  stream >> object.fReconstructedHits;
  stream >> object.fClusterDistances;
  return stream;
}

}

}
