/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_Tracker_Streamer_h
#define AC_Tracker_Streamer_h

#define AC_Tracker_Variables \
private: \
  Short_t fClusters; \
  TracksVector fTracks; \
  VerticesVector fVertices; \
public: \
  Tracker() \
    : fClusters(0) \
    , fTracks() \
    , fVertices() \
  { \
  }

#endif // AC_Tracker_Streamer_h
