/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TrackerTrackFit_Streamer_h
#define AC_TrackerTrackFit_Streamer_h

#define AC_TrackerTrackFit_Variables \
private: \
  UChar_t fParameters; \
  Float_t fRigidity; \
  Float_t fInverseRigidityError; \
  Float_t fChiSquareNormalizedX; \
  Float_t fChiSquareNormalizedY; \
  Float_t fThetaLayer1; \
  Float_t fPhiLayer1; \
  Float_t fXLayer1; \
  Float_t fYLayer1; \
  Float_t fXLayer1Plus1cm; \
  Float_t fYLayer1Plus1cm; \
  Float_t fXTRDUpper; \
  Float_t fYTRDUpper; \
  Float_t fXTRDCenter; \
  Float_t fYTRDCenter; \
  Float_t fXTRDLower; \
  Float_t fYTRDLower; \
  Float_t fThetaTOFUpper; \
  Float_t fPhiTOFUpper; \
  Float_t fXTOFUpper; \
  Float_t fYTOFUpper; \
  Float_t fXTOFUpperMinus1cm; \
  Float_t fYTOFUpperMinus1cm; \
  Float_t fXLayer56; \
  Float_t fYLayer56; \
  Float_t fThetaRICH; \
  Float_t fPhiRICH; \
  Float_t fXRICH; \
  Float_t fYRICH; \
  Float_t fThetaLayer9; \
  Float_t fPhiLayer9; \
  Float_t fXLayer9; \
  Float_t fYLayer9; \
  Float_t fXLayer9Minus1cm; \
  Float_t fYLayer9Minus1cm; \
public: \
  TrackerTrackFit() \
    : fParameters(0) \
    , fRigidity(0) \
    , fInverseRigidityError(0) \
    , fChiSquareNormalizedX(0) \
    , fChiSquareNormalizedY(0) \
    , fThetaLayer1(0) \
    , fPhiLayer1(0) \
    , fXLayer1(0) \
    , fYLayer1(0) \
    , fXLayer1Plus1cm(0) \
    , fYLayer1Plus1cm(0) \
    , fXTRDUpper(0) \
    , fYTRDUpper(0) \
    , fXTRDCenter(0) \
    , fYTRDCenter(0) \
    , fXTRDLower(0) \
    , fYTRDLower(0) \
    , fThetaTOFUpper(0) \
    , fPhiTOFUpper(0) \
    , fXTOFUpper(0) \
    , fYTOFUpper(0) \
    , fXTOFUpperMinus1cm(0) \
    , fYTOFUpperMinus1cm(0) \
    , fXLayer56(0) \
    , fYLayer56(0) \
    , fThetaRICH(0) \
    , fPhiRICH(0) \
    , fXRICH(0) \
    , fYRICH(0) \
    , fThetaLayer9(0) \
    , fPhiLayer9(0) \
    , fXLayer9(0) \
    , fYLayer9(0) \
    , fXLayer9Minus1cm(0) \
    , fYLayer9Minus1cm(0) \
  { \
  }

#endif // AC_TrackerTrackFit_Streamer_h
