/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TrackerReconstructedHit_Streamer_h
#define AC_TrackerReconstructedHit_Streamer_h

#define AC_TrackerReconstructedHit_Variables \
private: \
  Char_t fLayer; \
  Float_t fX; \
  Float_t fY; \
  Float_t fSignalX; \
  Float_t fSignal; \
  Short_t fResidualY; \
  Float_t fQLayerJ; \
public: \
  TrackerReconstructedHit() \
    : fLayer(0) \
    , fX(0) \
    , fY(0) \
    , fSignalX(0) \
    , fSignal(0) \
    , fResidualY(0) \
    , fQLayerJ(0) \
  { \
  }

#endif // AC_TrackerReconstructedHit_Streamer_h
