/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TRD_Streamer_h
#define AC_TRD_Streamer_h

#define AC_TRD_Variables \
private: \
  Short_t fNumberOfHits; \
  VTracksVector fVTracks; \
  HTracksVector fHTracks; \
  HSegmentsVector fHSegments; \
  RawHitsVector fRawHits; \
public: \
  TRD() \
    : fNumberOfHits(0) \
    , fVTracks() \
    , fHTracks() \
    , fHSegments() \
    , fRawHits() \
  { \
  }

#endif // AC_TRD_Streamer_h
