/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TRD.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TRD& object) {

  stream << object.fNumberOfHits;
  stream << object.fVTracks;
  stream << object.fHTracks;
  stream << object.fHSegments;
  stream << object.fRawHits;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TRD& object) {

  stream >> object.fNumberOfHits;
  stream >> object.fVTracks;
  stream >> object.fHTracks;
  stream >> object.fHSegments;
  stream >> object.fRawHits;
  return stream;
}

}

}
