/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TRDHTrack_Streamer_h
#define AC_TRDHTrack_Streamer_h

#define AC_TRDHTrack_Variables \
private: \
  UShort_t fStatus; \
  ChargesNewVector fChargesNew; \
  HSegmentIndexVector fHSegmentIndex; \
public: \
  TRDHTrack() \
    : fStatus(0) \
    , fChargesNew() \
    , fHSegmentIndex() \
  { \
  }

#endif // AC_TRDHTrack_Streamer_h
