/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TRDHSegment.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TRDHSegment& object) {

  stream << object.fRawHitIndex;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TRDHSegment& object) {

  if (::AC::CurrentACQtVersion() >= 50 && ::AC::CurrentACQtVersion() <= 56)
    stream >> object.fRawHitIndex_old;
  if (::AC::CurrentACQtVersion() >= 57)
    stream >> object.fRawHitIndex;
  return stream;
}

}

}
