/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TRDHSegment_Streamer_h
#define AC_TRDHSegment_Streamer_h

#define AC_TRDHSegment_Variables \
private: \
  RawHitIndexVector_8 fRawHitIndex_old; \
  RawHitIndexVector fRawHitIndex; \
public: \
  TRDHSegment() \
    : fRawHitIndex_old() \
    , fRawHitIndex() \
  { \
  }

#endif // AC_TRDHSegment_Streamer_h
