/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TRDRawHit.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TRDRawHit& object) {

  stream << object.fHWAddress;
  stream << object.fADC;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TRDRawHit& object) {


  UShortArrayStream<2> subStream1(stream);
  object.fHWAddress = subStream1.read();
  object.fADC = subStream1.read();

  return stream;
}

}

}
