/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_TRDRawHit_Streamer_h
#define AC_TRDRawHit_Streamer_h

#define AC_TRDRawHit_Variables \
private: \
  UShort_t fHWAddress; \
  UShort_t fADC; \
public: \
  TRDRawHit() \
    : fHWAddress(0) \
    , fADC(0) \
  { \
  }

#endif // AC_TRDRawHit_Streamer_h
