[Description]
Namespace = AC
Class = TRDVTrack
Members = \
  UShort_t fStatus                                  \
  Float_t fChiSquare                                \
  Float_t fTheta                                    \
  Float_t fPhi                                      \
  Float_t fX                                        \
  Float_t fY                                        \
  Float_t fZ                                        \
  UInt_t fPattern                                   \
  [53-ChargesVector fCharges]                       \
  [53-ChargesProbabilityVector fChargesProbability] \
  ChargesNewVector fChargesNew
