/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "TRDVTrack.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const TRDVTrack& object) {

  stream << object.fStatus;
  stream << object.fChiSquare;
  stream << object.fTheta;
  stream << object.fPhi;
  stream << object.fX;
  stream << object.fY;
  stream << object.fZ;
  stream << object.fPattern;
  stream << object.fChargesNew;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, TRDVTrack& object) {

  stream >> object.fStatus;

  FloatArrayStream<6> subStream1(stream);
  object.fChiSquare = subStream1.read();
  object.fTheta = subStream1.read();
  object.fPhi = subStream1.read();
  object.fX = subStream1.read();
  object.fY = subStream1.read();
  object.fZ = subStream1.read();

  stream >> object.fPattern;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fCharges;
  if (::AC::CurrentACQtVersion() < 53)
    stream >> object.fChargesProbability;
  stream >> object.fChargesNew;
  return stream;
}

}

}
