[Description]
Namespace = AC
Class = Trigger
Members = \
  UShort_t fTimeDifference \
  UInt_t fBits             \
  UShort_t fJMembPatt      \
  Float_t  fLiveTime       \
  UShort_t fTriggerRateFT  \
  UShort_t fTriggerRateFTC \
  UShort_t fTriggerRateFTZ \
  UShort_t fTriggerRateFTE \
  UShort_t fTriggerRateLV1
