/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_Trigger_Streamer_h
#define AC_Trigger_Streamer_h

#define AC_Trigger_Variables \
private: \
  UShort_t fTimeDifference; \
  UInt_t fBits; \
  UShort_t fJMembPatt; \
  Float_t fLiveTime; \
  UShort_t fTriggerRateFT; \
  UShort_t fTriggerRateFTC; \
  UShort_t fTriggerRateFTZ; \
  UShort_t fTriggerRateFTE; \
  UShort_t fTriggerRateLV1; \
  UInt_t fTofPatt1; \
public: \
  Trigger() \
    : fTimeDifference(0) \
    , fBits(0) \
    , fJMembPatt(0) \
    , fLiveTime(0) \
    , fTriggerRateFT(0) \
    , fTriggerRateFTC(0) \
    , fTriggerRateFTZ(0) \
    , fTriggerRateFTE(0) \
    , fTriggerRateLV1(0) \
    , fTofPatt1(0) \
  { \
  }

#endif // AC_Trigger_Streamer_h
