/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "Trigger.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const Trigger& object) {

  stream << object.fTimeDifference;
  stream << object.fBits;
  stream << object.fJMembPatt;
  stream << object.fLiveTime;
  stream << object.fTriggerRateFT;
  stream << object.fTriggerRateFTC;
  stream << object.fTriggerRateFTZ;
  stream << object.fTriggerRateFTE;
  stream << object.fTriggerRateLV1;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, Trigger& object) {

  stream >> object.fTimeDifference;
  stream >> object.fBits;
  stream >> object.fJMembPatt;
  stream >> object.fLiveTime;

  UShortArrayStream<5> subStream1(stream);
  object.fTriggerRateFT = subStream1.read();
  object.fTriggerRateFTC = subStream1.read();
  object.fTriggerRateFTZ = subStream1.read();
  object.fTriggerRateFTE = subStream1.read();
  object.fTriggerRateLV1 = subStream1.read();

  return stream;
}

}

}
