/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#include <QDataStream>
#include "Settings.h"
#include "Vertex.h"

namespace ACsoft {

namespace AC {

/** Writes this object into a QDataStream, which is used to produce ACQt files */
QDataStream& operator<<(QDataStream& stream, const Vertex& object) {

  stream << object.fX;
  stream << object.fY;
  stream << object.fZ;
  stream << object.fTheta;
  stream << object.fPhi;
  stream << object.fMomentum;
  stream << object.fGalacticLongitude;
  stream << object.fGalacticLatitude;
  stream << object.fFirstTrackIndex;
  stream << object.fSecondTrackIndex;
  return stream;
}

/** Reads this object from a QDataStream, which is used to construct AC objects from ACQt files */
QDataStream& operator>>(QDataStream& stream, Vertex& object) {


  FloatArrayStream<8> subStream1(stream);
  object.fX = subStream1.read();
  object.fY = subStream1.read();
  object.fZ = subStream1.read();
  object.fTheta = subStream1.read();
  object.fPhi = subStream1.read();
  object.fMomentum = subStream1.read();
  object.fGalacticLongitude = subStream1.read();
  object.fGalacticLatitude = subStream1.read();


  UCharArrayStream<2> subStream2(stream);
  object.fFirstTrackIndex = subStream2.read();
  object.fSecondTrackIndex = subStream2.read();

  return stream;
}

}

}
