/* This file was generated by acqt_streamer_generator from the corresponding IDL file. DO NOT EDIT MANUALLY! */

#ifndef AC_Vertex_Streamer_h
#define AC_Vertex_Streamer_h

#define AC_Vertex_Variables \
private: \
  Float_t fX; \
  Float_t fY; \
  Float_t fZ; \
  Float_t fTheta; \
  Float_t fPhi; \
  Float_t fMomentum; \
  Float_t fGalacticLongitude; \
  Float_t fGalacticLatitude; \
  UChar_t fFirstTrackIndex; \
  UChar_t fSecondTrackIndex; \
public: \
  Vertex() \
    : fX(0) \
    , fY(0) \
    , fZ(0) \
    , fTheta(0) \
    , fPhi(0) \
    , fMomentum(0) \
    , fGalacticLongitude(0) \
    , fGalacticLatitude(0) \
    , fFirstTrackIndex(0) \
    , fSecondTrackIndex(0) \
  { \
  }

#endif // AC_Vertex_Streamer_h
