[Description]
Namespace = AC
Class = Vertex
Members = \
  Float_t fX \
  Float_t fY \
  Float_t fZ \
  Float_t fTheta \
  Float_t fPhi \
  Float_t fMomentum \
  Float_t fGalacticLongitude \
  Float_t fGalacticLatitude \
  UChar_t fFirstTrackIndex \
  UChar_t fSecondTrackIndex
