TEMPLATE = lib

DESTDIR = $$(ACROOTSOFTWARE)/lib

INCLUDEPATH += $$(ACROOTSOFTWARE) $$(ACROOTSOFTWARE)/acroot $$(ACROOTSOFTWARE)/analysis $$(ACROOTSOFTWARE)/io $$(ACROOTSOFTWARE)/detector $$(ACROOTSOFTWARE)/interface $$(ACROOTSOFTWARE)/producer $$(ACROOTSOFTWARE)/trdcalibration $$(ACROOTSOFTWARE)/utilities $$(ACROOTSOFTWARE)/cuts

DEPENDPATH += $$INCLUDEPATH

LIBS += -L$$(ACROOTSOFTWARE)/lib

include($$(ACROOTSOFTWARE)/aux/AC.pri)
include($$(ACROOTSOFTWARE)/aux/ACrootcint.pri)
