//  $Id: commons.C,v 1.408 2011/02/09 03:53:09 choutko Exp $


#include "commons.h"
#include "cern.h"
#include "amsdbc.h"

//
STATUSFFKEY_DEF STATUSFFKEY;
SELECTFFKEY_DEF SELECTFFKEY;
AMSFFKEY_DEF AMSFFKEY;
IOPA_DEF IOPA;
//=============================
TFMCFFKEY_DEF TFMCFFKEY;
TFREFFKEY_DEF TFREFFKEY;
TFCAFFKEY_DEF TFCAFFKEY;
//=============================
//=============================
ECMCFFKEY_DEF ECMCFFKEY;
ECREFFKEY_DEF ECREFFKEY;
ECCAFFKEY_DEF ECCAFFKEY;
//=============================
ATGEFFKEY_DEF ATGEFFKEY;
ATMCFFKEY_DEF ATMCFFKEY;
ATREFFKEY_DEF ATREFFKEY;
ATCAFFKEY_DEF ATCAFFKEY;
//=============================
#ifndef _PGTRACK_
TKGEOMFFKEY_DEF TKGEOMFFKEY;
TRFITFFKEY_DEF TRFITFFKEY;
TRCLFFKEY_DEF TRCLFFKEY;
TRCALIB_DEF TRCALIB;
TRALIG_DEF TRALIG;
TRMCFFKEY_DEF TRMCFFKEY;
MAGSFFKEY_DEF MAGSFFKEY;
#else
TKFIELD_DEF TKFIELD;
#endif
TRDMCFFKEY_DEF TRDMCFFKEY;
TRDFITFFKEY_DEF TRDFITFFKEY;
TRDRECFFKEY_DEF TRDRECFFKEY;
TRDCLFFKEY_DEF TRDCLFFKEY;
MISCFFKEY_DEF MISCFFKEY;
BETAFITFFKEY_DEF BETAFITFFKEY;
CHARGEFITFFKEY_DEF CHARGEFITFFKEY;

CCFFKEY_DEF CCFFKEY;
GMFFKEY_DEF GMFFKEY; //ISN

CALIB_DEF CALIB;
TRDCALIB_DEF TRDCALIB;
G4FFKEY_DEF G4FFKEY;
//=============================
TGL1FFKEY_DEF TGL1FFKEY;
//=============================
DAQCFFKEY_DEF DAQCFFKEY;
LVL3FFKEY_DEF LVL3FFKEY;
LVTMFFKEY_DEF LVTMFFKEY;
LVL3SIMFFKEY_DEF LVL3SIMFFKEY;
LVL3EXPFFKEY_DEF LVL3EXPFFKEY;
TRMFFKEY_DEF TRMFFKEY;
//
RICGEOM_DEF RICGEOM;
RICCONTROLFFKEY_DEF RICCONTROLFFKEY;
RICFFKEY_DEF RICFFKEY;
RICRECFFKEY_DEF RICRECFFKEY;
RICRADSETUPFFKEY_DEF RICRADSETUPFFKEY;
RICDBFFKEY_DEF RICDBFFKEY;
PRODFFKEY_DEF PRODFFKEY;
// Geant  commons

GCFLAG_DEF GCFLAG;
GCLINK_DEF GCLINK;
GCVOLU_DEF GCVOLU;
GCTMED_DEF GCTMED;
GCTRAK_DEF GCTRAK;
GCKINE_DEF GCKINE;

HVSEC_DEF  HVSEC;
          
