#ifndef COMMONS_C
#define COMMONS_C


#include <commons.h>
SELECTFFKEY_DEF SELECTFFKEY;
AMSFFKEY_DEF AMSFFKEY;
IOPA_DEF IOPA;
TOFMCFFKEY_DEF TOFMCFFKEY;
TOFRECFFKEY_DEF TOFRECFFKEY;
CTCMCFFKEY_DEF CTCMCFFKEY;
CTCGEOMFFKEY_DEF CTCGEOMFFKEY;
CTCRECFFKEY_DEF CTCRECFFKEY;
TRMCFFKEY_DEF TRMCFFKEY;
BETAFITFFKEY_DEF BETAFITFFKEY;
CHARGEFITFFKEY_DEF CHARGEFITFFKEY;
TRFITFFKEY_DEF TRFITFFKEY;
CCFFKEY_DEF CCFFKEY;
TRCLFFKEY_DEF TRCLFFKEY;


// Geant  commons

GCFLAG_DEF GCFLAG;
GCLINK_DEF GCLINK;
GCVOLU_DEF GCVOLU;
GCTMED_DEF GCTMED;
GCTRAK_DEF GCTRAK;
GCKINE_DEF GCKINE;

// Fortran commons
//TKFIELD_DEF TKFIELD;

#endif /* !defined(COMMONS_C) */
