//  $Id: commons.C,v 1.403 2008/11/06 09:56:34 pzuccon Exp $


#include <unistd.h>
#include <sys/types.h>
#include <sys/time.h>
#include "commons.h"
#include <stdlib.h>
#include <iostream.h>
#include "cern.h"
#include "amsdbc.h"
#include <fstream.h>
//
STATUSFFKEY_DEF STATUSFFKEY;
SELECTFFKEY_DEF SELECTFFKEY;
AMSFFKEY_DEF AMSFFKEY;
IOPA_DEF IOPA;
//=============================
TFMCFFKEY_DEF TFMCFFKEY;
TFREFFKEY_DEF TFREFFKEY;
TFCAFFKEY_DEF TFCAFFKEY;
//=============================
MAGSFFKEY_DEF MAGSFFKEY;
//=============================
ECMCFFKEY_DEF ECMCFFKEY;
ECREFFKEY_DEF ECREFFKEY;
ECCAFFKEY_DEF ECCAFFKEY;
//=============================
ATGEFFKEY_DEF ATGEFFKEY;
ATMCFFKEY_DEF ATMCFFKEY;
ATREFFKEY_DEF ATREFFKEY;
ATCAFFKEY_DEF ATCAFFKEY;
//=============================
TKGEOMFFKEY_DEF TKGEOMFFKEY;
TRMCFFKEY_DEF TRMCFFKEY;
TRDMCFFKEY_DEF TRDMCFFKEY;
TRDFITFFKEY_DEF TRDFITFFKEY;
TRDRECFFKEY_DEF TRDRECFFKEY;
TRDCLFFKEY_DEF TRDCLFFKEY;
MISCFFKEY_DEF MISCFFKEY;
BETAFITFFKEY_DEF BETAFITFFKEY;
CHARGEFITFFKEY_DEF CHARGEFITFFKEY;
TRFITFFKEY_DEF TRFITFFKEY;
CCFFKEY_DEF CCFFKEY;
GMFFKEY_DEF GMFFKEY; //ISN
TRCLFFKEY_DEF TRCLFFKEY;
TRCALIB_DEF TRCALIB;
CALIB_DEF CALIB;
TRDCALIB_DEF TRDCALIB;
TRALIG_DEF TRALIG;
G4FFKEY_DEF G4FFKEY;
//=============================
TGL1FFKEY_DEF TGL1FFKEY;
//=============================
DAQCFFKEY_DEF DAQCFFKEY;
LVL3FFKEY_DEF LVL3FFKEY;
LVL3SIMFFKEY_DEF LVL3SIMFFKEY;
LVL3EXPFFKEY_DEF LVL3EXPFFKEY;
TRMFFKEY_DEF TRMFFKEY;
//
RICGEOM_DEF RICGEOM;
RICCONTROLFFKEY_DEF RICCONTROLFFKEY;
RICFFKEY_DEF RICFFKEY;
RICRECFFKEY_DEF RICRECFFKEY;
RICRADSETUPFFKEY_DEF RICRADSETUPFFKEY;
PRODFFKEY_DEF PRODFFKEY;
// Geant  commons

GCFLAG_DEF GCFLAG;
GCLINK_DEF GCLINK;
GCVOLU_DEF GCVOLU;
GCTMED_DEF GCTMED;
GCTRAK_DEF GCTRAK;
GCKINE_DEF GCKINE;

// Fortran commons
// TKFIELD_DEF TKFIELD;
// AMSDATADIR_DEF AMSDATADIR

