//  $Id: commons.C,v 1.390 2008/08/27 18:17:37 pzuccon Exp $


#include "commons.h"
//
STATUSFFKEY_DEF STATUSFFKEY;
SELECTFFKEY_DEF SELECTFFKEY;
AMSFFKEY_DEF AMSFFKEY;
IOPA_DEF IOPA;
//=============================
TFMCFFKEY_DEF TFMCFFKEY;
TFREFFKEY_DEF TFREFFKEY;
TFCAFFKEY_DEF TFCAFFKEY;
//=============================
MAGSFFKEY_DEF MAGSFFKEY;
//=============================
ECMCFFKEY_DEF ECMCFFKEY;
ECREFFKEY_DEF ECREFFKEY;
ECCAFFKEY_DEF ECCAFFKEY;
//=============================
ATGEFFKEY_DEF ATGEFFKEY;
ATMCFFKEY_DEF ATMCFFKEY;
ATREFFKEY_DEF ATREFFKEY;
ATCAFFKEY_DEF ATCAFFKEY;
//=============================
TRDMCFFKEY_DEF TRDMCFFKEY;
TRDFITFFKEY_DEF TRDFITFFKEY;
TRDRECFFKEY_DEF TRDRECFFKEY;
TRDCLFFKEY_DEF TRDCLFFKEY;
MISCFFKEY_DEF MISCFFKEY;
BETAFITFFKEY_DEF BETAFITFFKEY;
CHARGEFITFFKEY_DEF CHARGEFITFFKEY;
CCFFKEY_DEF CCFFKEY;
GMFFKEY_DEF GMFFKEY; //ISN
CALIB_DEF CALIB;
TRDCALIB_DEF TRDCALIB;
G4FFKEY_DEF G4FFKEY;
//=============================
TGL1FFKEY_DEF TGL1FFKEY;
//=============================
DAQCFFKEY_DEF DAQCFFKEY;
LVL3FFKEY_DEF LVL3FFKEY;
LVL3SIMFFKEY_DEF LVL3SIMFFKEY;
LVL3EXPFFKEY_DEF LVL3EXPFFKEY;
TRMFFKEY_DEF TRMFFKEY;
//
RICGEOM_DEF RICGEOM;
RICCONTROLFFKEY_DEF RICCONTROLFFKEY;
RICFFKEY_DEF RICFFKEY;
RICRECFFKEY_DEF RICRECFFKEY;
RICRADSETUPFFKEY_DEF RICRADSETUPFFKEY;
PRODFFKEY_DEF PRODFFKEY;
// Geant  commons

//GCFLAG_DEF GCFLAG;
//GCLINK_DEF GCLINK;
//GCVOLU_DEF GCVOLU;
//GCTMED_DEF GCTMED;
//GCTRAK_DEF GCTRAK;
//GCKINE_DEF GCKINE;

// Fortran commons
// TKFIELD_DEF TKFIELD;
// AMSDATADIR_DEF AMSDATADIR

