//  $Id: root.C,v 1.18 2002/03/20 09:41:21 choumilo Exp $
#include <root.h>
#include <ntuple.h>
#ifdef __WRITEROOT__
EventNtuple02::EventNtuple02(){}
BetaNtuple02::BetaNtuple02(){}
ChargeNtuple02::ChargeNtuple02(){}
ParticleNtuple02::ParticleNtuple02(){}
TOFClusterNtuple::TOFClusterNtuple(){}
TOFMCClusterNtuple::TOFMCClusterNtuple(){}
TrClusterNtuple::TrClusterNtuple(){}
TrMCClusterNtuple::TrMCClusterNtuple(){}
TRDMCClusterNtuple::TRDMCClusterNtuple(){}
TRDRawHitNtuple::TRDRawHitNtuple(){}
TRDClusterNtuple::TRDClusterNtuple(){}
TRDSegmentNtuple::TRDSegmentNtuple(){}
TRDTrackNtuple::TRDTrackNtuple(){}
TrRecHitNtuple02::TrRecHitNtuple02(){}
TrTrackNtuple02::TrTrackNtuple02(){}
MCEventGNtuple02::MCEventGNtuple02(){}
MCTrackNtuple::MCTrackNtuple(){}
AntiClusterNtuple::AntiClusterNtuple(){}
ANTIMCClusterNtuple::ANTIMCClusterNtuple(){}
LVL1Ntuple02::LVL1Ntuple02(){}
LVL3Ntuple02::LVL3Ntuple02(){}
TrRawClusterNtuple::TrRawClusterNtuple(){}
AntiRawClusterNtuple::AntiRawClusterNtuple(){}
TOFRawClusterNtuple::TOFRawClusterNtuple(){}
EcalShowerNtuple::EcalShowerNtuple(){}
EcalClusterNtuple::EcalClusterNtuple(){}
Ecal2DClusterNtuple::Ecal2DClusterNtuple(){}
EcalHitNtuple::EcalHitNtuple(){}
RICMCNtuple::RICMCNtuple(){}
RICEventNtuple::RICEventNtuple(){}
RICRing::RICRing(){}
//ClassImp(AMSNtuple)
ClassImp(EventNtuple02)
ClassImp(BetaNtuple02)
ClassImp(ChargeNtuple02)
ClassImp(ParticleNtuple02)
ClassImp(TOFClusterNtuple)
ClassImp(TOFMCClusterNtuple)
ClassImp(TrClusterNtuple)
ClassImp(TrMCClusterNtuple)
ClassImp(TRDMCClusterNtuple)
ClassImp(TRDRawHitNtuple)
ClassImp(TRDClusterNtuple)
ClassImp(TRDSegmentNtuple)
ClassImp(TRDTrackNtuple)
ClassImp(TrRecHitNtuple02)
ClassImp(TrTrackNtuple02)
ClassImp(MCEventGNtuple02)
ClassImp(MCTrackNtuple)
ClassImp(AntiClusterNtuple)
ClassImp(ANTIMCClusterNtuple)
ClassImp(LVL1Ntuple02)
ClassImp(LVL3Ntuple02)
ClassImp(TrRawClusterNtuple)
ClassImp(AntiRawClusterNtuple)
ClassImp(TOFRawClusterNtuple)
ClassImp(EcalShowerNtuple)
ClassImp(EcalClusterNtuple)
ClassImp(Ecal2DClusterNtuple)
ClassImp(EcalHitNtuple)
ClassImp(RICMCNtuple)
ClassImp(RICEventNtuple)
ClassImp(RICRing)
#endif
