//  $Id: root.C,v 1.13 2001/07/20 20:24:51 kscholbe Exp $
#include <root.h>
#include <ntuple.h>
#ifdef __WRITEROOT__
ClassImp(AMSNtuple)
ClassImp(EventNtuple)
ClassImp(EventNtuple02)
ClassImp(BetaNtuple)
ClassImp(BetaNtuple02)
ClassImp(ChargeNtuple)
ClassImp(ChargeNtuple02)
ClassImp(ParticleNtuple)
ClassImp(ParticleNtuple02)
ClassImp(TOFClusterNtuple)
ClassImp(TOFMCClusterNtuple)
ClassImp(TrClusterNtuple)
ClassImp(TrMCClusterNtuple)
ClassImp(TRDMCClusterNtuple)
ClassImp(TRDRawHitNtuple)
ClassImp(TRDClusterNtuple)
ClassImp(TRDSegmentNtuple)
ClassImp(TRDTrackNtuple)
ClassImp(TrRecHitNtuple)
ClassImp(TrRecHitNtuple02)
ClassImp(TrTrackNtuple)
ClassImp(TrTrackNtuple02)
ClassImp(MCEventGNtuple)
ClassImp(MCEventGNtuple02)
ClassImp(MCTrackNtuple)
ClassImp(CTCClusterNtuple)
ClassImp(CTCMCClusterNtuple)
ClassImp(AntiClusterNtuple)
ClassImp(ANTIMCClusterNtuple)
ClassImp(LVL3Ntuple)
ClassImp(LVL1Ntuple)
ClassImp(LVL1Ntuple02)
ClassImp(CTCHitNtuple)
ClassImp(TrRawClusterNtuple)
ClassImp(AntiRawClusterNtuple)
ClassImp(TOFRawClusterNtuple)
ClassImp(EcalShowerNtuple)
ClassImp(EcalClusterNtuple)
ClassImp(EcalHitNtuple)
ClassImp(RICMCNtuple)
ClassImp(RICEventNtuple)
ClassImp(RICRing)
#endif
