#define gspart g3spart
#define gfpart g3fpart
#define gskpho g3skpho
#define ggckov g3gckov
#define gtckov g3tckov
#define gufld  gufldvmc
#define gutrev g3utrev
#define glisur g3lisur
#define gvrop g3vrop
#define gnckov g3nckov
#define gdrot g3drot
#define gevkev g3evkev
#define gphini g3phini
#define gphxsi g3phxsi
#define gwork g3work
#define gprobi g3probi
#define gdrela g3drela
#define gbrela g3brela
#define gprela g3prela
#define gphoti g3photi
#define grayli g3rayli
#define gannii g3annii
#define gcompi g3compi
#define gbrsga g3brsga
#define gprsga g3prsga
#define gdrsga g3drsg
#define gmunui g3munui
#define gpfisi g3pfisi
#define grangi g3rangi
#define gcoeff g3coeff
#define gstini g3stini
#define gmulof g3mulof
#define gvrot g3vrot
#define gphysi g3physi
#define gbirk g3birk
#define gpoiss g3poiss

#define Gufld Gufldvmc

#define GPOISS G3POISS
#define GBIRK G3BIRK
#define GSPART G3SPART
#define GFPART G3FPART
#define GSKPHO G3SKPHO
#define GGCKOV G3GCKOV
#define GTCKOV G3TCKOV
#define GUFLD  GUFLDVMC
#define GMUNUI G3MUNUI
#define GPFISI G3PFISI
#define GRANGI G3RANGI
#define GCOEFF G3COEFF
#define GSTINI G3STINI
#define GMULOF G3MULOF
#define GUTREV G3UTREV 
#define GLISUR G3LISUR
#define GVROP G3VROP
#define GNCKOV G3NCKOV
#define GDROT G3DROT
#define GEVKEV G3EVKEV
#define GPHINI G3PHINI
#define GPHXSI G3PHXSI
#define GWORK G3WORK
#define GPROBI G3PROBI
#define GDRELA G3DRELA
#define GBRELA G3BRELA
#define GPRELA G3PRELA
#define GPHOTI G3PHOTI
#define GRAYLI G3RAYLI
#define GANNII G3ANNII
#define GCOMPI G3COMPI
#define GBRSGA G3BRSGA
#define GPRSGA G3PRSGA
#define GDRSGA G3DRSGA
#define GVROT G3VROT
#define GPHYSI G3PHYSI
