{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Fri Nov  7 13:49:41 1997 by ROOT version 1.03/06)
//   from TTree h1/Converted
//   found on file: prmu.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = new TFile("prmu.root");
   TTree *h1 = (TTree*)f->Get("h1");

//Declaration of leaves types
   Int_t           eventno;
   Int_t           run;
   Int_t           runtype;
   Int_t           time[2];
   Float_t         Polephi;
   Float_t         Thetas;
   Float_t         Phis;
   Int_t           Particles;
   Int_t           Tracks;
   Int_t           Betas;
   Int_t           Charges;
   Int_t           Trrechits;
   Int_t           Trclusters;
   Int_t           Trmcclusters;
   Int_t           Tofclusters;
   Int_t           Tofmcclusters;
   Int_t           Ctcclusters;
   Int_t           Ctcmcclusters;
   Int_t           Antimcclusters;
   Int_t           Anticlusters;
   Int_t           nbeta;
   Int_t           betapattern[10];
   Float_t         beta[10];
   Float_t         betaerror[10];
   Float_t         betachi2[10];
   Int_t           ncharge;
   Float_t         chargebetap[70];
   Int_t           chargetof[70];
   Int_t           chargetracker[70];
   Float_t         probtof[10][7];
   Float_t         probtracker[10][7];
   Int_t           npart;
   Int_t           pctcp[30][2];
   Int_t           pbetap[60];
   Int_t           pchargep[60];
   Int_t           ptrackp[60];
   Int_t           pid[60];
   Float_t         pmass[60];
   Float_t         perrmass[60];
   Float_t         pmom[60];
   Float_t         perrmom[60];
   Float_t         pcharge[60];
   Float_t         ptheta[60];
   Float_t         pphi[60];
   Float_t         pcoo[20][3];
   Float_t         signalctc[30][2];
   Float_t         betactc[30][2];
   Float_t         errorbetactc[30][2];
   Float_t         cooctc[30][2];
   Int_t           ntof;
   Int_t           Tofstatus[60];
   Int_t           plane[60];
   Int_t           bar[60];
   Float_t         Tofedep[60];
   Float_t         Toftime[60];
   Float_t         Tofetime[60];
   Float_t         Tofcoo[20][3];
   Float_t         Tofercoo[20][3];
   Int_t           ntofmc;
   Int_t           Tofmcidsoft[200];
   Float_t         Tofmcxcoo[66][3];
   Float_t         Tofmctof[200];
   Float_t         Tofmcedep[200];
   Int_t           ntrcl;
   Int_t           Idsoft[250];
   Int_t           Statust[250];
   Int_t           Neleml[250];
   Int_t           Nelemr[250];
   Float_t         Sumt[250];
   Float_t         Sigmat[250];
   Float_t         Meant[250];
   Float_t         Rmst[250];
   Float_t         Errormeant[250];
   Float_t         Amplitude[50][5];
   Int_t           ntrclmc;
   Int_t           Idsoftmc[200];
   Int_t           Itra[200];
   Int_t           Left[100][2];
   Int_t           Center[100][2];
   Int_t           Right[100][2];
   Float_t         ss[100][2];
   Float_t         xca[66][3];
   Float_t         xcb[66][3];
   Float_t         xgl[66][3];
   Float_t         summc[200];
   Int_t           ntrrh;
   Int_t           px[200];
   Int_t           py[200];
   Int_t           statusr[200];
   Int_t           Layer[200];
   Float_t         hitr[66][3];
   Float_t         ehitr[66][3];
   Float_t         sumr[200];
   Float_t         difosum[200];
   Int_t           ntrtr;
   Int_t           trstatus[20];
   Int_t           pattern[20];
   Int_t           nhits[20];
   Int_t           phits[3][6];
   Int_t           Fastfitdone[20];
   Int_t           Geanefitdone[20];
   Int_t           Advancedfitdone[20];
   Float_t         Chi2strline[20];
   Float_t         Chi2circle[20];
   Float_t         Circleridgidity[20];
   Float_t         Chi2fastfit[20];
   Float_t         Ridgidity[20];
   Float_t         Errridgidity[20];
   Float_t         Theta[20];
   Float_t         phi[20];
   Float_t         p0[6][3];
   Float_t         gchi2[20];
   Float_t         gridgidity[20];
   Float_t         gerrridgidity[20];
   Float_t         gtheta[20];
   Float_t         gphi[20];
   Float_t         gp0[6][3];
   Float_t         hchi2[10][2];
   Float_t         Hridgidity[10][2];
   Float_t         Herrridgidity[10][2];
   Float_t         htheta[10][2];
   Float_t         hphi[10][2];
   Float_t         hp0[10][2];
   Float_t         fchi2ms[20];
   Float_t         gchi2ms[20];
   Float_t         ridgidityms[20];
   Float_t         gridgidityms[20];
   Int_t           nmcg;
   Int_t           nskip[20];
   Int_t           Particle[20];
   Float_t         coo[6][3];
   Float_t         dir[6][3];
   Float_t         momentum[20];
   Float_t         mass[20];
   Float_t         charge[20];
   Int_t           nctccl;
   Int_t           Ctcstatus[20];
   Int_t           Ctclayer[20];
   Float_t         ctccoo[6][3];
   Float_t         ctcercoo[6][3];
   Float_t         ctcrawsignal[20];
   Float_t         ctcsignal[20];
   Float_t         ctcesignal[20];
   Int_t           nctcclmc;
   Int_t           Ctcmcidsoft[200];
   Float_t         Ctcmcxcoo[66][3];
   Float_t         Ctcmcxdir[66][3];
   Float_t         Ctcstep[200];
   Float_t         ctccharge[200];
   Float_t         ctcbeta[200];
   Float_t         ctcedep[200];
   Int_t           nanti;
   Int_t           Antistatus[48];
   Int_t           Antisector[48];
   Float_t         Antiedep[48];
   Float_t         Anticoo[16][3];
   Float_t         Antiercoo[16][3];
   Int_t           nantimc;
   Int_t           Antimcidsoft[200];
   Float_t         Antimcxcoo[66][3];
   Float_t         Antimctof[200];
   Float_t         Antimcedep[200];
   Int_t           nlvl3;
   Int_t           Lvl3toftr[2];
   Int_t           Lvl3antitr[2];
   Int_t           Lvl3trackertr[2];
   Int_t           Lvl3ntrhits[2];
   Int_t           Lvl3npat[2];
   Int_t           Lvl3pattern[1][2];
   Float_t         Lvl3residual[1][2];
   Float_t         Lvl3time[2];
   Int_t           nlvl1;
   Int_t           Lvl1mode[1];
   Int_t           Lvl1flag[1];
   Int_t           Lvl1tofpatt[0][4];
   Int_t           Lvl1antipatt[1];
   Int_t           nctcht;
   Int_t           Ctchitstatus[50];
   Int_t           Ctchitlayer[50];
   Int_t           ctchitcolumn[50];
   Int_t           ctchitrow[50];
   Float_t         ctchitsignal[50];

//Set branch addresses
   h1->SetBranchAddress("eventno",&eventno);
   h1->SetBranchAddress("run",&run);
   h1->SetBranchAddress("runtype",&runtype);
   h1->SetBranchAddress("time",time);
   h1->SetBranchAddress("Polephi",&Polephi);
   h1->SetBranchAddress("Thetas",&Thetas);
   h1->SetBranchAddress("Phis",&Phis);
   h1->SetBranchAddress("Particles",&Particles);
   h1->SetBranchAddress("Tracks",&Tracks);
   h1->SetBranchAddress("Betas",&Betas);
   h1->SetBranchAddress("Charges",&Charges);
   h1->SetBranchAddress("Trrechits",&Trrechits);
   h1->SetBranchAddress("Trclusters",&Trclusters);
   h1->SetBranchAddress("Trmcclusters",&Trmcclusters);
   h1->SetBranchAddress("Tofclusters",&Tofclusters);
   h1->SetBranchAddress("Tofmcclusters",&Tofmcclusters);
   h1->SetBranchAddress("Ctcclusters",&Ctcclusters);
   h1->SetBranchAddress("Ctcmcclusters",&Ctcmcclusters);
   h1->SetBranchAddress("Antimcclusters",&Antimcclusters);
   h1->SetBranchAddress("Anticlusters",&Anticlusters);
   h1->SetBranchAddress("nbeta",&nbeta);
   h1->SetBranchAddress("betapattern",betapattern);
   h1->SetBranchAddress("beta",beta);
   h1->SetBranchAddress("betaerror",betaerror);
   h1->SetBranchAddress("betachi2",betachi2);
   h1->SetBranchAddress("ncharge",&ncharge);
   h1->SetBranchAddress("chargebetap",chargebetap);
   h1->SetBranchAddress("chargetof",chargetof);
   h1->SetBranchAddress("chargetracker",chargetracker);
   h1->SetBranchAddress("probtof",probtof);
   h1->SetBranchAddress("probtracker",probtracker);
   h1->SetBranchAddress("npart",&npart);
   h1->SetBranchAddress("pctcp",pctcp);
   h1->SetBranchAddress("pbetap",pbetap);
   h1->SetBranchAddress("pchargep",pchargep);
   h1->SetBranchAddress("ptrackp",ptrackp);
   h1->SetBranchAddress("pid",pid);
   h1->SetBranchAddress("pmass",pmass);
   h1->SetBranchAddress("perrmass",perrmass);
   h1->SetBranchAddress("pmom",pmom);
   h1->SetBranchAddress("perrmom",perrmom);
   h1->SetBranchAddress("pcharge",pcharge);
   h1->SetBranchAddress("ptheta",ptheta);
   h1->SetBranchAddress("pphi",pphi);
   h1->SetBranchAddress("pcoo",pcoo);
   h1->SetBranchAddress("signalctc",signalctc);
   h1->SetBranchAddress("betactc",betactc);
   h1->SetBranchAddress("errorbetactc",errorbetactc);
   h1->SetBranchAddress("cooctc",cooctc);
   h1->SetBranchAddress("ntof",&ntof);
   h1->SetBranchAddress("Tofstatus",Tofstatus);
   h1->SetBranchAddress("plane",plane);
   h1->SetBranchAddress("bar",bar);
   h1->SetBranchAddress("Tofedep",Tofedep);
   h1->SetBranchAddress("Toftime",Toftime);
   h1->SetBranchAddress("Tofetime",Tofetime);
   h1->SetBranchAddress("Tofcoo",Tofcoo);
   h1->SetBranchAddress("Tofercoo",Tofercoo);
   h1->SetBranchAddress("ntofmc",&ntofmc);
   h1->SetBranchAddress("Tofmcidsoft",Tofmcidsoft);
   h1->SetBranchAddress("Tofmcxcoo",Tofmcxcoo);
   h1->SetBranchAddress("Tofmctof",Tofmctof);
   h1->SetBranchAddress("Tofmcedep",Tofmcedep);
   h1->SetBranchAddress("ntrcl",&ntrcl);
   h1->SetBranchAddress("Idsoft",Idsoft);
   h1->SetBranchAddress("Statust",Statust);
   h1->SetBranchAddress("Neleml",Neleml);
   h1->SetBranchAddress("Nelemr",Nelemr);
   h1->SetBranchAddress("Sumt",Sumt);
   h1->SetBranchAddress("Sigmat",Sigmat);
   h1->SetBranchAddress("Meant",Meant);
   h1->SetBranchAddress("Rmst",Rmst);
   h1->SetBranchAddress("Errormeant",Errormeant);
   h1->SetBranchAddress("Amplitude",Amplitude);
   h1->SetBranchAddress("ntrclmc",&ntrclmc);
   h1->SetBranchAddress("Idsoftmc",Idsoftmc);
   h1->SetBranchAddress("Itra",Itra);
   h1->SetBranchAddress("Left",Left);
   h1->SetBranchAddress("Center",Center);
   h1->SetBranchAddress("Right",Right);
   h1->SetBranchAddress("ss",ss);
   h1->SetBranchAddress("xca",xca);
   h1->SetBranchAddress("xcb",xcb);
   h1->SetBranchAddress("xgl",xgl);
   h1->SetBranchAddress("summc",summc);
   h1->SetBranchAddress("ntrrh",&ntrrh);
   h1->SetBranchAddress("px",px);
   h1->SetBranchAddress("py",py);
   h1->SetBranchAddress("statusr",statusr);
   h1->SetBranchAddress("Layer",Layer);
   h1->SetBranchAddress("hitr",hitr);
   h1->SetBranchAddress("ehitr",ehitr);
   h1->SetBranchAddress("sumr",sumr);
   h1->SetBranchAddress("difosum",difosum);
   h1->SetBranchAddress("ntrtr",&ntrtr);
   h1->SetBranchAddress("trstatus",trstatus);
   h1->SetBranchAddress("pattern",pattern);
   h1->SetBranchAddress("nhits",nhits);
   h1->SetBranchAddress("phits",phits);
   h1->SetBranchAddress("Fastfitdone",Fastfitdone);
   h1->SetBranchAddress("Geanefitdone",Geanefitdone);
   h1->SetBranchAddress("Advancedfitdone",Advancedfitdone);
   h1->SetBranchAddress("Chi2strline",Chi2strline);
   h1->SetBranchAddress("Chi2circle",Chi2circle);
   h1->SetBranchAddress("Circleridgidity",Circleridgidity);
   h1->SetBranchAddress("Chi2fastfit",Chi2fastfit);
   h1->SetBranchAddress("Ridgidity",Ridgidity);
   h1->SetBranchAddress("Errridgidity",Errridgidity);
   h1->SetBranchAddress("Theta",Theta);
   h1->SetBranchAddress("phi",phi);
   h1->SetBranchAddress("p0",p0);
   h1->SetBranchAddress("gchi2",gchi2);
   h1->SetBranchAddress("gridgidity",gridgidity);
   h1->SetBranchAddress("gerrridgidity",gerrridgidity);
   h1->SetBranchAddress("gtheta",gtheta);
   h1->SetBranchAddress("gphi",gphi);
   h1->SetBranchAddress("gp0",gp0);
   h1->SetBranchAddress("hchi2",hchi2);
   h1->SetBranchAddress("Hridgidity",Hridgidity);
   h1->SetBranchAddress("Herrridgidity",Herrridgidity);
   h1->SetBranchAddress("htheta",htheta);
   h1->SetBranchAddress("hphi",hphi);
   h1->SetBranchAddress("hp0",hp0);
   h1->SetBranchAddress("fchi2ms",fchi2ms);
   h1->SetBranchAddress("gchi2ms",gchi2ms);
   h1->SetBranchAddress("ridgidityms",ridgidityms);
   h1->SetBranchAddress("gridgidityms",gridgidityms);
   h1->SetBranchAddress("nmcg",&nmcg);
   h1->SetBranchAddress("nskip",nskip);
   h1->SetBranchAddress("Particle",Particle);
   h1->SetBranchAddress("coo",coo);
   h1->SetBranchAddress("dir",dir);
   h1->SetBranchAddress("momentum",momentum);
   h1->SetBranchAddress("mass",mass);
   h1->SetBranchAddress("charge",charge);
   h1->SetBranchAddress("nctccl",&nctccl);
   h1->SetBranchAddress("Ctcstatus",Ctcstatus);
   h1->SetBranchAddress("Ctclayer",Ctclayer);
   h1->SetBranchAddress("ctccoo",ctccoo);
   h1->SetBranchAddress("ctcercoo",ctcercoo);
   h1->SetBranchAddress("ctcrawsignal",ctcrawsignal);
   h1->SetBranchAddress("ctcsignal",ctcsignal);
   h1->SetBranchAddress("ctcesignal",ctcesignal);
   h1->SetBranchAddress("nctcclmc",&nctcclmc);
   h1->SetBranchAddress("Ctcmcidsoft",Ctcmcidsoft);
   h1->SetBranchAddress("Ctcmcxcoo",Ctcmcxcoo);
   h1->SetBranchAddress("Ctcmcxdir",Ctcmcxdir);
   h1->SetBranchAddress("Ctcstep",Ctcstep);
   h1->SetBranchAddress("ctccharge",ctccharge);
   h1->SetBranchAddress("ctcbeta",ctcbeta);
   h1->SetBranchAddress("ctcedep",ctcedep);
   h1->SetBranchAddress("nanti",&nanti);
   h1->SetBranchAddress("Antistatus",Antistatus);
   h1->SetBranchAddress("Antisector",Antisector);
   h1->SetBranchAddress("Antiedep",Antiedep);
   h1->SetBranchAddress("Anticoo",Anticoo);
   h1->SetBranchAddress("Antiercoo",Antiercoo);
   h1->SetBranchAddress("nantimc",&nantimc);
   h1->SetBranchAddress("Antimcidsoft",Antimcidsoft);
   h1->SetBranchAddress("Antimcxcoo",Antimcxcoo);
   h1->SetBranchAddress("Antimctof",Antimctof);
   h1->SetBranchAddress("Antimcedep",Antimcedep);
   h1->SetBranchAddress("nlvl3",&nlvl3);
   h1->SetBranchAddress("Lvl3toftr",Lvl3toftr);
   h1->SetBranchAddress("Lvl3antitr",Lvl3antitr);
   h1->SetBranchAddress("Lvl3trackertr",Lvl3trackertr);
   h1->SetBranchAddress("Lvl3ntrhits",Lvl3ntrhits);
   h1->SetBranchAddress("Lvl3npat",Lvl3npat);
   h1->SetBranchAddress("Lvl3pattern",Lvl3pattern);
   h1->SetBranchAddress("Lvl3residual",Lvl3residual);
   h1->SetBranchAddress("Lvl3time",Lvl3time);
   h1->SetBranchAddress("nlvl1",&nlvl1);
   h1->SetBranchAddress("Lvl1mode",Lvl1mode);
   h1->SetBranchAddress("Lvl1flag",Lvl1flag);
   h1->SetBranchAddress("Lvl1tofpatt",Lvl1tofpatt);
   h1->SetBranchAddress("Lvl1antipatt",Lvl1antipatt);
   h1->SetBranchAddress("nctcht",&nctcht);
   h1->SetBranchAddress("Ctchitstatus",Ctchitstatus);
   h1->SetBranchAddress("Ctchitlayer",Ctchitlayer);
   h1->SetBranchAddress("ctchitcolumn",ctchitcolumn);
   h1->SetBranchAddress("ctchitrow",ctchitrow);
   h1->SetBranchAddress("ctchitsignal",ctchitsignal);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// h1->SetBranchStatus("*",0);  // disable all branches
// h1->SetBranchStatus("branchname",1);  // activate branchname

   Int_t nentries = h1->GetEntries();

   Int_t nbytes = 0;
//   for (Int_t i=0; i<nentries;i++) {
//      nbytes += h1->GetEvent(i);
//   }
}
