#!/bin/tcsh
if ( "$1" != "" )  then
setenv AMSWD $1
endif

if ( "$2" != "" )  then
setenv ADDBUILDNO 1
else
unsetenv ADDBUILDNO
endif

unsetenv ARCH
unsetenv PGTRACK
source /Offline/vdev/install/amsvar.icc64
source /Offline/vdev/install/g4i
gmake cleanALL
gmake allg4
source /Offline/vdev/install/amsvar.gcc64
gmake allp
source /Offline/vdev/install/amsvar.icc32
gmake allold 
setenv PGTRACK 1
source /Offline/vdev/install/amsvar.icc64
source /Offline/vdev/install/g4i
gmake allg4
source /Offline/vdev/install/amsvar.gcc32
source /Offline/vdev/install/g4i
gmake allg4
source /Offline/vdev/install/amsvar.gcc64
gmake allp
source /Offline/vdev/install/amsvar.icc32
gmake allold 
