#!/bin/tcsh
if ( "$1" != "" )  then
setenv AMSWD $1
endif
unsetenv PGTRACK
unsetenv ARCH
source /Offline/vdev/install/amsvar
gmake all
source /Offline/vdev/install/amsvar.slc4
gmake all
source /Offline/vdev/install/amsvar.slc4icc
setenv ARCH Linux.24
gmake allold 
unsetenv ARCH
setenv PGTRACK 1
source /Offline/vdev/install/amsvar
gmake all
source /Offline/vdev/install/amsvar.slc4
gmake all
source /Offline/vdev/install/amsvar.slc4icc
setenv ARCH Linux.24
gmake allold
unsetenv ARCH
