#!/bin/tcsh
unsetenv CASTORSTATIC
setenv ROOTSYS /afs/cern.ch/ams/Offline/root/linux/root-v5-34-9-icc64.14-mic 
setenv ROOTSYSRUN /afs/cern.ch/ams/Offline/root/linux/root-v5-34-9-gcc64-slc6/
setenv LD_LIBRARY_PATH $ROOTSYS/lib:$ROOTSYSRUN/lib
setenv PGTRACK 1
unsetenv G4AMS
setenv NORFIOD 1
source /afs/cern.ch/sw/IntelSoftware/linux/all-setup.csh 
source /afs/cern.ch/sw/IntelSoftware/linux/x86_64/xe2015/composerxe/bin/compilervars.csh   intel64
setenv INTELDIR /afs/cern.ch/sw/IntelSoftware/linux/x86_64
setenv INTELVER xe2015/composer_xe_2015.1.133

