#!/bin/tcsh
unsetenv CASTORSTATIC
setenv ROOTSYS /afs/cern.ch/ams/Offline/root/linux/root-v5-34-9-icc64.14-mic
setenv ROOTSYSRUN /afs/cern.ch/ams/Offline/root/linux/root-v5-34-9-gcc64-slc6/
setenv LD_LIBRARY_PATH $ROOTSYS/lib:$ROOTSYSRUN/lib
setenv PGTRACK 1
unsetenv G4AMS
setenv NORFIOD 1

setenv GEANT4NEW 1
unsetenv CLHEP_BASE_DIR
setenv G4AMS 1
setenv PGTRACK 1
setenv G4MULTITHREADED 1
unsetenv DEBUGFLAG
setenv G4SYSTEM  Linuxk1omic-icc-mt
setenv G4USE_STL 1
setenv OGLHOME /usr
setenv  G4WORKDIR /tmp
setenv G4INSTALL /afs/cern.ch/ams/Offline/geant4.10.01.p01-ams
setenv G4LIB $G4INSTALL/lib
setenv G4_NO_VERBOSE 1
setenv G4VIS_BUILD_DAWNFILE_DRIVER 1
setenv G4VIS_BUILD_DAWN_DRIVER         1
setenv G4VIS_USE_DAWN       1
setenv G4VIS_USE_DAWNFILE         1
setenv G4VIS_BUILD_OPENGLX_DRIVER     1  # Uses OpenGL and Motif
setenv G4VIS_BUILD_OPENGLXM_DRIVER     1  # Uses OpenGL and Motif
setenv G4VIS_USE_OPENGLX     1
#setenv G4VIS_BUILD_OPENGLQT_DRIVER 1
unsetenv G4VIS_USE_OPENGLXM
setenv G4VIS_BUILD_RAYTRACERX_DRIVER         1
setenv G4VIS_USE_HEPREP 1
setenv G4VIS_BUILD_HEPREPFILE_DRIVER         1
setenv G4VIS_USE_HEPREPFILE         1
setenv G4UI_BUILD 1
setenv G4VIS_BUILD_ASCIITREE_DRIVER 1
setenv G4VIS_USE_ASCIITREE 1
setenv G4LEVELGAMMADATA  $G4INSTALL/data/PhotonEvaporation3.1
setenv G4RADIOACTIVEDATA  $G4INSTALL/data/RadioactiveDecay4.2
setenv G4LEDATA $G4INSTALL/data/G4EMLOW6.41
setenv NeutronHPCrossSections $G4INSTALL/data/G4NDL4.5
setenv G4NEUTRONXSDATA $G4INSTALL/data/G4NEUTRONXS1.4
gmake -j 40
gmake producer 
