#!/bin/tcsh
if ( "$1" != "" )  then
setenv AMSWD $1
endif

if ( "$2" != "" )  then
setenv ADDBUILDNO 1
else
unsetenv ADDBUILDNO
endif
setenv PREFIX /Offline/vdev/install
setenv TESTFLAG

source $PREFIX/amsvar$TESTFLAG.icc64
setenv ARCH linuxx8664icc
echo
echo "******* Loading $ARCH *******"
echo
root -b -q load.C
root -b -q loadPG.C

source $PREFIX/amsvar$TESTFLAG.gcc64
setenv ARCH linuxx8664gcc
echo
echo "******* Loading $ARCH *******"
echo
root -b -q load.C
root -b -q loadPG.C

#source $PREFIX/amsvar$TESTFLAG.icc32
#setenv ARCH linuxicc
#echo
#echo "******* Loading $ARCH *******"
#echo
#root -b -q load.C
#root -b -q loadPG.C

#source $PREFIX/amsvar$TESTFLAG.gcc32
#setenv ARCH linux
#echo
#echo "******* Loading $ARCH ******* "
#echo
#root -b -q load.C
#root -b -q loadPG.C

unsetenv ARCH




