#! /bin/sh

setenv PLATFORM $1

setenv ROOTSYS /offline/root/$PLATFORM/v3.05.03gcc322
setenv PATH "${PATH}:$ROOTSYS/bin"
setenv LIBPATH "$ROOTSYS/lib"
setenv LD_LIBRARY_PATH "${LD_LIBRARY_PATH}:$ROOTSYS/lib"


