#!/bin/tcsh
if ( "$1" != "" )  then
setenv AMSWD $1
endif

if ( "$2" != "" )  then
setenv ADDBUILDNO 1
else
unsetenv ADDBUILDNO
endif

unsetenv PGTRACK
unsetenv ARCH
source /Offline/vdev/install/amsvar.icc32
../examples/g3.root.test.job
source /Offline/vdev/install/amsvar.slc4
../examples/g3.root.test.job
source /Offline/vdev/install/amsvar.icc64
../examples/g3.root.test.job
source /Offline/vdev/install/amsvar.slc4icc
setenv ARCH Linux.24
../examples/g3.root.test.job
unsetenv ARCH
setenv PGTRACK 1
source /Offline/vdev/install/amsvar.icc32
../examples/g3.root.test.job
source /Offline/vdev/install/amsvar.slc4
../examples/g3.root.test.job
source /Offline/vdev/install/amsvar.icc64
../examples/g3.root.test.job
source /Offline/vdev/install/amsvar.slc4icc
setenv ARCH Linux.24
../examples/g3.root.test.job
unsetenv ARCH
unsetenv PGTRACK
