#!/bin/tcsh
if ( "$1" != "" )  then
setenv AMSWD $1
endif

if ( "$2" != "" )  then
setenv ADDBUILDNO 1
else
unsetenv ADDBUILDNO
endif

setenv ARCH linuxicc
echo "Testing $ARCH"
$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
set i=$?
if ( "$i" < 0 ) then
echo "$ARCH failed $i"
endif


setenv ARCH PGlinuxicc
echo "Testing $ARCH"
$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
set i=$?
if ( "$i" < 0 ) then
echo "$ARCH failed $i"
endif


setenv ARCH PGLinux.24
echo "Testing $ARCH"

$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
set i=$?
if ( "$i" < 0 ) then
echo "$ARCH failed $i"
endif




setenv ARCH linux
echo "Testing $ARCH"
$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
set i=$?
if ( "$i" < 0 ) then
echo "$ARCH failed $i"
endif

setenv ARCH Linux.24
echo "Testing $ARCH"
$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
set i=$?
if ( "$i" < 0 ) then
echo "$ARCH failed $i"
endif



setenv ARCH PGlinux
echo "Testing $ARCH"
$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
set i=$?
if ( "$i" < 0 ) then
echo "$ARCH failed $i"
endif


setenv ARCH linuxx8664icc
echo "Testing $ARCH"
$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
set i=$?
if ( "$i" < 0 ) then
echo "$ARCH failed $i"
endif



setenv ARCH PGlinuxx8664icc
echo "Testing $ARCH"
$AMSWD/exe/linuxicc/fastntrd/fastntrd.exe g3v1g3$ARCH.root 10 1 10
set i=$?
if ( "$i" < 0 ) then
echo "$ARCH failed $i"
endif

unsetenv ARCH




