#!/bin/tcsh
# define environment library variable for ROOT

setenv AMSGeoDir `pwd`

set os = `uname`

if ($os == "AIX") then

  setenv LIBPATH $ROOTSYS/lib':'`pwd`/bin;

else if ($os == "OSF1" || $os == "Linux") then

  setenv LD_LIBRARY_PATH $ROOTSYS/lib':'`pwd`/bin;

else if ($os == "HP-UX") then

  setenv SHLIB_PATH $ROOTSYS/lib':'`pwd`/bin;

endif
