//  $Id: root.cxx,v 1.2 2001/08/23 21:05:55 kscholbe Exp $
/*#include "AMSR_Rootclasses.h"
ClassImp(EventNtuple02)
ClassImp(BetaNtuple02)
ClassImp(ChargeNtuple02)
ClassImp(ParticleNtuple02)
ClassImp(TOFClusterNtuple)
ClassImp(TOFMCClusterNtuple)
ClassImp(TrClusterNtuple)
ClassImp(TrMCClusterNtuple)
ClassImp(TRDMCClusterNtuple)
ClassImp(TRDRawHitNtuple)
ClassImp(TRDClusterNtuple)
ClassImp(TRDSegmentNtuple)
ClassImp(TRDTrackNtuple)
ClassImp(TrRecHitNtuple02)
ClassImp(TrTrackNtuple02)
ClassImp(MCEventGNtuple02)
ClassImp(MCTrackNtuple)
ClassImp(AntiClusterNtuple)
ClassImp(ANTIMCClusterNtuple)
ClassImp(LVL3Ntuple)
ClassImp(LVL1Ntuple02)
ClassImp(TrRawClusterNtuple)
ClassImp(AntiRawClusterNtuple)
ClassImp(TOFRawClusterNtuple)
ClassImp(EcalShowerNtuple)
ClassImp(EcalClusterNtuple)
ClassImp(Ecal2DClusterNtuple)
ClassImp(EcalHitNtuple)
ClassImp(RICMCNtuple)
ClassImp(RICEventNtuple)
ClassImp(RICRing) */
