//  $Id: linkdef.h,v 1.10 2001/07/13 16:25:34 choutko Exp $
#ifdef __CINT__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class AMSNtuple;
#pragma link C++ class BetaNtuple;
#pragma link C++ class BetaNtuple02;
#pragma link C++ class ChargeNtuple;
#pragma link C++ class ChargeNtuple02;
#pragma link C++ class ParticleNtuple;
#pragma link C++ class ParticleNtuple02;
#pragma link C++ class TOFClusterNtuple;
#pragma link C++ class TOFMCClusterNtuple;
#pragma link C++ class TrClusterNtuple;
#pragma link C++ class TrMCClusterNtuple;
#pragma link C++ class TRDMCClusterNtuple;
#pragma link C++ class TRDClusterNtuple;
#pragma link C++ class TRDSegmentNtuple;
#pragma link C++ class TRDTrackNtuple;
#pragma link C++ class TRDRawHitNtuple;
#pragma link C++ class TrRecHitNtuple;
#pragma link C++ class TrRecHitNtuple02;
#pragma link C++ class TrTrackNtuple;
#pragma link C++ class TrTrackNtuple02;
#pragma link C++ class MCEventGNtuple;
#pragma link C++ class MCEventGNtuple02;
#pragma link C++ class MCTrackNtuple;
#pragma link C++ class CTCClusterNtuple;
#pragma link C++ class CTCMCClusterNtuple;
#pragma link C++ class AntiClusterNtuple;
#pragma link C++ class ANTIMCClusterNtuple;
#pragma link C++ class LVL3Ntuple;
#pragma link C++ class LVL1Ntuple;
#pragma link C++ class LVL1Ntuple02;
#pragma link C++ class CTCHitNtuple;
#pragma link C++ class TrRawClusterNtuple;
#pragma link C++ class AntiRawClusterNtuple;
#pragma link C++ class TOFRawClusterNtuple;
#pragma link C++ class RICMCNtuple;
#pragma link C++ class RICEventNtuple;
#pragma link C++ class RICRing;
#pragma link C++ class EcalClusterNtuple;
#pragma link C++ class EcalShowerNtuple;
#pragma link C++ class EcalHitNtuple;
#pragma link C++ class EventNtuple;
#pragma link C++ class EventNtuple02;
#endif
