#pragma prefix "ams.cern.ch"
module DPS{
   typedef unsigned long time;
  interface Client{

   struct NominalClient{
    short MaxClients;
    float CPUNeeded; 
    short MemoryNeeded;
    string WholeScriptPath;
    string LogPath;
    string SubmitCommand;
   }; 

    enum ClientStatus{Unknown,Submitted,Registered,Busy,Idle,Lost};

    enum ClientType{Generic,Server,Consumer,Producer,Monitor};

    struct CID{
    string HostName;
    unsigned long uid;
    unsigned long pid;
    unsigned long ppid;
    };

    struct ActiveClient{
     CID id;
     string IOR;
     time LastUpdate;
     time Start;
     ClientStatus Status;
     ClientType   Type;
   };

    typedef sequence<ActiveClient> ACS;
    void getACL(out ACS acl);

    typedef sequence<NominalClient> NCS;
    void  getNCL(out NCS ncl);
      
    boolean sendId(in CID id, in long Propagate, in long Error);      
   
   enum HostStatus{NoResponse,LastClientFailed,OK};
   struct ActiveHost{
      string HostName;
      HostStatus Status;
      short ClientsRunning;
      short ClientsAllowed; 
      long ClientsProcessed;
      long ClientsFailed;
      time LastUpdate;
   };

  };
 
  interface Producer: Client{
    typedef sequence<octet> TDV;
    TDV getTDV(in string name, in time Insert, in time Begin, in time End);
    void sendTDV(in TDV tdv, in string name, in time Insert, in time Begin, in time End, in long Propagate, in long Error );
    enum RunStatus{Failed,ToBeRerun, Processing, Finished};
     struct RunEvInfo{
     unsigned long Run;
     long FirstEvent;
     long LastEvent;
     long Priority;
     string FilePath;
     RunStatus Status;
     string OutputDirPath;
     long UpdateFreq;
     long DieHard;
     time SubmitTime;
    };
/*
    enum RunStatus{ToBeRerun, Processing, Finished};
    struct RunEvE{
      RunEv rv;
      long Priority;
      RunStatus Status;
    };
    typedef sequence<RunEvE> RunEvTable;
    RunEvTable getRunEvTable();
    void sendRunEvTable(in RunEvTable ret);
*/
    RunEvInfo getRunEvInfo(in long Propagate, in long Error);
    struct CurrentInfo{
      CID id;
      unsigned long Run;
      long EvenstProcessed;     
      long LastEventProcessed;
      long ErrorsFound;
      float CPUTimeSpent;
    }; 
    void sendCurrentInfo(in CurrentInfo ci, in long Propagate, in long Error); 
 
    struct TDVTableEntry{
     unsigned long CRC;
     time Insert;
     time Begin;
     time End;
    };
    typedef sequence<TDVTableEntry> TDVTable; 
    TDVTable getTDVTable(in string Name, in unsigned long Run,in long Propagate, in long Error);     
    
    enum DSTStatus{Success,Failure};
    struct DSTEnd{
     time   Insert;
     time   Begin;
     time   End;
     long   FirstEvent;
     long   LastEvent;
     long   EventNumber;
     DSTStatus Status;
    };    
    struct NtupleEnd{
     string NtupleName;
     string NtuplePath;
     DSTEnd dn;
    };
    void sendNtupleEnd(in NtupleEnd ne, in long Propagate, in long Error); 
    
    struct EventStatusEnd{
     TDV body;
     DSTEnd dn;
    };
    void sendEventStatusEnd(in EventStatusEnd ee, in long Propagate, in long Error); 
    
    
/*

    struct RSChange{
     unsigned long Run;
     RunStatus Status;
    };
    void SendRunStatus(in RSChange status, in long Propagate, in long Error); 
*/
    struct EndRunInfo{
     CID id;
     unsigned long Run;
     long EventsProcessed;
     long ErrorsFound;
    };

    void sendEndRunInfo(in EndRunInfo er,in long Propagate, in long Error); 
    
  };

  interface Server: Client{

    enum OpType{StartServer,StartClient,KillServer,KillClient,ClearStartServer,
    ClearStartClient, ClearKillServer, ClearKillClient};

    struct CriticalOps{
     time TimeOut;
     OpType Action;
     time TimeStamp;
    };
    void sendCriticalOps(in CriticalOps op, in long Propagate,in long Error);
    void sendACL(in ACS acl, in long Propagate,in long Error);
    void sendNCL(in NCS ncl, in long Propagate,in long Error);
    void ping();
   struct NominalHost{
    string HostName;
    string Interface;
    string OS;
    short   CPUNumber;
    short   Memory;
    long    Clock;      
   };
   
    typedef sequence<ActiveHost> AHS;
    void getAHL(out AHS ahl);
    void sendAHL(in AHS ahl, in long Propagate,in long Error);
   };
  interface Monitor: Client{
  };
  
};
