#!/bin/sh
sqlplus amsdes/@@amsdb  <<!
set echo on
drop table mods;
create  table mods (
tabname varchar2(63),
modtime date
)
/
insert into mods values('jobs', '24-oct-05');
insert into mods values('runs', '25-oct-05');
insert into mods values('datasets','25-oct-05');
 
create or replace trigger jobs_biu
after insert or update on jobs
for each row
begin
update mods set modtime=sysdate where tabname='jobs';
end ;
/
show errors

CREATE OR REPLACE
    FUNCTION date_to_unixts(oracle_date IN DATE) RETURN PLS_INTEGER IS
        /**
         * Converts an Oracle DATE to a UNIX timestamp
         */
        unix_epoch DATE := TO_DATE('19700101000000','YYYYMMDDHH24MISS');
        max_date DATE := TO_DATE('20380101000000','YYYYMMDDHH24MISS');
        min_date DATE := TO_DATE('19030101000000','YYYYMMDDHH24MISS');
        unix_ts PLS_INTEGER;
        
        BEGIN
            
            IF oracle_date > max_date THEN
                RAISE_APPLICATION_ERROR( -20902,'Date too large for 32bit UNIX timestamp' );
            ELSIF oracle_date < min_date THEN
                RAISE_APPLICATION_ERROR( -20902,'Date too small for 32bit UNIX timestamp' );
            ELSE
                unix_ts := (oracle_date - unix_epoch) / (1/86400);
            END IF;
            
            RETURN (unix_ts);
        
        END;
/
   show errors
!
